import type { RdlWorkbookMappingProfile } from "./RdlWorkbookMappingProfile.ts";

export const CCUS_CFIHOS_FORMAT_PROFILE: RdlWorkbookMappingProfile = {
  profileKey: "ccus-cfihos-format-v1",
  adapterVersion: "1.0.0",
  sourceKey: "ccus",
  sourceName: "CCUS RDL Extension",
  sourceDescription: "Proposed CCUS Reference Data Library extension using the CFIHOS workbook tab structure.",
  publisher: "RDL Explorer candidate source",
  releaseKey: "ccus-0.1-draft",
  versionLabel: "0.1 draft",
  releaseStatus: "candidate",
  workbookPath: "data/rdl/ccus/CCUS_RDL_Extension_CFIHOS_Format.xlsx",
  sourceUri: "repo://data/rdl/ccus/CCUS_RDL_Extension_CFIHOS_Format.xlsx",
  sheetNames: {
    tagClass: "tag class",
    equipmentClass: "equipment class",
    property: "property",
    documentType: "document type",
    discipline: "discipline",
    unit: "unit of measure",
    sourceStandard: "source standard",
    handoverEvent: "handover event",
    controlledValue: "property picklist values",
    informationRequirement: "Jip33 info required spec",
    tagClassProperty: "tag class property",
    equipmentClassProperty: "equipment class property",
    disciplineDocument: "discipline document type",
    tagEquipment: "tag equipment class relationshi",
    classDocument: "document required per class",
    classSourceStandard: "tag or equip class src standard",
    sourceMapping: "tag equip class prop src std",
  },
  fields: {
    id: ["CFIHOS unique code", "CFIHOS Property ID"],
    tagClassId: ["tag class CFIHOS unique code", "CFIHOS unique code"],
    tagClassName: ["tag class name"],
    tagClassDefinition: ["tag class definition"],
    tagParentName: ["parent tag class name"],
    equipmentClassId: ["equipment class CFIHOS unique code"],
    equipmentClassName: ["equipment class name"],
    equipmentClassDefinition: ["equipment class definition"],
    equipmentParentName: ["parent equipment class name"],
    propertyId: ["property CFIHOS unique code", "CFIHOS Property ID", "CFIHOS unique code"],
    propertyName: ["property name", "Property Name"],
    propertyDefinition: ["property definition", "Definition"],
    propertyDataType: ["property data type", "Data Type"],
    propertyLength: ["property data type length", "Length"],
    propertyUnitId: ["unit of measure dimension code CFIHOS unique code", "Unit Class ID", "unit class or picklist reference"],
    propertyPicklistId: ["property picklist name CFIHOS unique code", "Picklist ID"],
    documentId: ["document type CFIHOS unique code", "CFIHOS unique code"],
    documentName: ["document type name"],
    documentDefinition: ["document type description", "description"],
    documentShortCode: ["document type short code", "short code"],
    documentClassification: ["document type classification", "classification"],
    disciplineId: ["discipline CFIHOS unique code", "CFIHOS unique code"],
    disciplineName: ["discipline name"],
    disciplineDescription: ["discipline description"],
    disciplineCode: ["discipline code"],
    disciplineRefCode: ["discipline code"],
    unitId: ["unit of measure CFIHOS unique code", "CFIHOS unique code"],
    unitName: ["unit of measure name"],
    unitSymbol: ["unit of measure symbol"],
    unitDimensionName: ["unit of measure dimension name"],
    sourceStandardId: ["source standard CFIHOS unique code", "source standard code CFIHOS unique code", "CFIHOS unique code"],
    sourceStandardCode: ["source standard code"],
    sourceStandardDescription: ["source standard description"],
    handoverId: ["CFIHOS unique code"],
    handoverName: ["handover event name"],
    handoverDescription: ["handover event description"],
    picklistId: ["property picklist CFIHOS unique code", "Property Picklist ID"],
    picklistName: ["property picklist name", "Picklist Name"],
    picklistValueId: ["property picklist value CFIHOS unique code", "Picklist Value ID"],
    picklistValueCode: ["property picklist value code", "Value Code"],
    picklistValueDescription: ["property picklist value description", "Value Description"],
    informationRequirementId: ["Source standard document and data requirement CFIHOS unique code", "source standard document and data requirement CFIHOS unique code"],
    informationRequirementNumber: ["source standard document and data requirement number", "requirement number"],
    informationRequirementTitle: ["source standard document and data requirement title", "requirement title"],
    informationRequirementDescription: ["source standard document and data requirement description", "requirement description"],
    relationshipId: ["relationship CFIHOS unique code"],
    classId: ["tag or equipment class CFIHOS unique code"],
    mappingId: ["tag or equipment class property source standard CFIHOS unique code", "CFIHOS unique code"],
  },
};
