import type { RdlWorkbookMappingProfile } from "./RdlWorkbookMappingProfile.ts";

export const WATER_DESALINATION_PROFILE: RdlWorkbookMappingProfile = {
  profileKey: "water-desalination-normalized-v1",
  adapterVersion: "1.1.0",
  sourceKey: "water-desalination",
  sourceName: "Water / Desalination RDL Extension",
  sourceDescription: "Proposed Water / Desalination Reference Data Library extension normalized through the generic workbook mapping layer.",
  publisher: "RDL Explorer candidate source",
  releaseKey: "water-desalination-0.1-draft",
  versionLabel: "0.1 draft",
  releaseStatus: "candidate",
  workbookPath: "data/rdl/water-desalination/Water_Desalination_RDL_Extension_CFIHOS_Format.xlsx",
  sourceUri: "repo://data/rdl/water-desalination/Water_Desalination_RDL_Extension_CFIHOS_Format.xlsx",
  sheetNames: {
    tagClass: "tag class",
    equipmentClass: "equipment class",
    property: "property",
    documentType: "document type",
    discipline: "discipline",
    unit: "unit of measure",
    sourceStandard: "source standard",
    handoverEvent: "handover event",
    controlledValue: "property picklist values",
    informationRequirement: "Jip33 info required spec",
    tagClassProperty: "tag class property",
    equipmentClassProperty: "equipment class property",
    disciplineDocument: "discipline document type",
    tagEquipment: "tag equipment class relationshi",
    classDocument: "document required per class",
    classSourceStandard: "tag or equip class src standard",
    sourceMapping: "tag equip class prop src std",
  },
  fields: {
    tagClassId: ["tag class code"],
    tagClassName: ["tag class name"],
    tagClassDefinition: ["description"],
    tagParentId: ["parent class code"],
    equipmentClassId: ["equipment class code"],
    equipmentClassName: ["equipment class name"],
    equipmentClassDefinition: ["description"],
    equipmentParentId: ["parent class code"],
    propertyId: ["property code"],
    propertyName: ["property name"],
    propertyDefinition: ["description"],
    propertyUnitId: ["unit of measure"],
    propertyPicklistId: ["picklist name"],
    documentId: ["document type code"],
    documentName: ["document type name"],
    documentDefinition: ["description"],
    documentClassification: ["definition file"],
    disciplineId: ["discipline code"],
    disciplineName: ["discipline name"],
    disciplineDescription: ["description"],
    disciplineCode: ["discipline code"],
    disciplineRefCode: ["discipline code"],
    unitId: ["unit code"],
    unitName: ["unit name"],
    unitSymbol: ["unit code"],
    unitDimensionName: ["quantity kind"],
    unitDescription: ["usage note"],
    sourceStandardId: ["source standard code"],
    sourceStandardCode: ["source standard code"],
    sourceStandardName: ["source standard name"],
    sourceStandardDescription: ["description"],
    handoverId: ["handover event code"],
    handoverName: ["handover event name"],
    handoverDescription: ["description"],
    handoverSequence: ["sequence"],
    picklistId: ["picklist name"],
    picklistName: ["picklist name"],
    picklistValueCode: ["value"],
    picklistValueDescription: ["value"],
    picklistValueSequence: ["sequence"],
    informationRequirementId: ["requirement code"],
    informationRequirementNumber: ["requirement code"],
    informationRequirementTitle: ["property name"],
    informationRequirementDescription: ["requirement statement"],
    informationRequirementClassId: ["equipment class code"],
    informationRequirementPropertyId: ["property code"],
    informationRequirementLevel: ["requirement level"],
    relationshipId: ["relationship code"],
    classId: ["object code", "equipment class code", "tag class code"],
    mappingId: ["mapping code"],
    mappingNote: ["mapping note"],
    mandatory: ["mandatory indicator"],
    relevance: ["property relevant indicator"],
    requirementLevel: ["requirement level"],
    relationshipType: ["relationship type"],
  },
};
