import { authenticateEnterpriseSsoIdentity, EnterpriseIdentityError, IDENTITY_ADMIN_ROLE } from "../../server/auth/EnterpriseIdentity.ts";
import { getRdlDatabaseClient } from "../../server/db/runtime.ts";
import { DatabaseRuntimeError } from "../../server/db/PgJsonClient.ts";
import { EnterpriseIdentityRepository } from "../../server/rdl/EnterpriseIdentityRepository.ts";
import { EnterpriseIdentityService } from "../../server/rdl/EnterpriseIdentityService.ts";
import { RuntimeConfigurationError, assertRuntimeEnvironment } from "../../server/runtime/environment.ts";
import type { ApiRequest, ApiResponse } from "../governance/_shared.ts";
export type {ApiRequest,ApiResponse};
export function identityContext(request:ApiRequest){assertRuntimeEnvironment();const identity=authenticateEnterpriseSsoIdentity(request.headers);const repository=new EnterpriseIdentityRepository(getRdlDatabaseClient());const service=new EnterpriseIdentityService(repository);return{identity,repository,service}}
export async function identityAdminContext(request:ApiRequest){const ctx=identityContext(request);const session=await ctx.service.session(ctx.identity);const bootstrap=(process.env.RDL_IDENTITY_BOOTSTRAP_ADMINS??"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);if(session.status!=="active")throw new EnterpriseIdentityError(403,"The enterprise identity is disabled.");const roles=[...session.roles];if(bootstrap.includes(ctx.identity.subject.toLowerCase())||bootstrap.includes(ctx.identity.email.toLowerCase()))roles.push(IDENTITY_ADMIN_ROLE);if(!roles.includes(IDENTITY_ADMIN_ROLE))throw new EnterpriseIdentityError(403,"The authenticated user is not authorized for identity administration.");return{...ctx,session:{...session,roles:[...new Set(roles)].sort()}}}
export function parseBody<T>(value:unknown):T{if(typeof value==="string")return JSON.parse(value) as T;if(value&&typeof value==="object"&&!Array.isArray(value))return value as T;throw new Error("A JSON request body is required.")}
export function handleIdentityError(response:ApiResponse,error:unknown){if(error instanceof EnterpriseIdentityError){response.status(error.statusCode).json({error:error.message});return}if(error instanceof RuntimeConfigurationError||error instanceof DatabaseRuntimeError){response.status(503).json({error:"The enterprise identity service is temporarily unavailable."});return}const message=error instanceof Error?error.message:"Unexpected identity service error.";const status=/required|invalid|cannot|not found/i.test(message)?400:500;response.status(status).json({error:status===500?"The enterprise identity service could not complete the request.":message})}
