import { Link } from "react-router-dom";
import { ArrowRight, CheckCircle2, CircleHelp, FileJson, FileSpreadsheet, Mail, Search } from "lucide-react";
import "./HelpPage.css";

const PILOT_FEEDBACK_EMAIL = "alessandro@papioconsulting.eu";
const sections = [["getting-started", "Getting started"], ["pilot", "Pilot status"], ["navigation", "Navigation & search"], ["classes", "Classes"], ["information", "Information"], ["reference", "Reference"], ["model", "Data Model"], ["validation", "Validation"], ["cis", "CIS Builder"], ["assistant", "AI Assistant"], ["workflows", "Common workflows"], ["feedback", "Feedback"]];

function GuideSection({ id, title, children }: { id: string; title: string; children: React.ReactNode }) { return <section className="guide-section" id={id}><h2>{title}</h2>{children}</section>; }

export function HelpPage() {
  return (
    <div className="guide-page">
      <aside className="guide-toc"><div className="guide-toc-title"><CircleHelp size={17}/> User Guide</div>{sections.map(([id,label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside>
      <article className="guide-content">
        <header className="guide-header"><div className="help-eyebrow">HOW TO USE THE APPLICATION</div><h1>CFIHOS Explorer User Guide</h1><p>Use this guide to understand the navigation, major capabilities, pilot limitations and recommended workflows in CFIHOS Explorer.</p></header>

        <GuideSection id="getting-started" title="Getting started"><p>The Explorer is organized around the CFIHOS reference model and the workflows built on top of it. A useful starting pattern is <strong>Explore → Understand → Validate → Build CIS → Ask AI</strong>.</p><div className="guide-callout"><strong>Tip</strong><span>If you are unsure where to begin, ask the <Link to="/assistant">AI Assistant</Link> what you want to accomplish. It can explain relevant Explorer capabilities and provide safe navigation actions.</span></div></GuideSection>

        <GuideSection id="pilot" title="Pilot status & data source"><p>This deployment is a <strong>pilot</strong> intended for controlled demonstration, evaluation and user feedback. Do not treat it as a production system or as a substitute for contractual review of the governing CFIHOS source.</p><p>The Explorer currently uses a reviewed <strong>CFIHOS 2.0 workbook snapshot</strong> committed with the application. The Validation workspace provides reproducible evidence about that snapshot and known upstream observations.</p><div className="guide-callout"><CheckCircle2 size={17}/><span>When a result matters to a project or contract decision, verify the CFIHOS identifier, provenance and source evidence shown by the Explorer.</span></div></GuideSection>

        <GuideSection id="navigation" title="Navigation & search"><p>The left sidebar groups pages by purpose. On smaller screens, use the menu button in the top bar to open the navigation.</p><ul><li><strong>Explore</strong> gives the application overview.</li><li><strong>Classes</strong> contains Tag and Equipment Classes.</li><li><strong>Information</strong> contains Document Types, Disciplines and Lifecycle Requirements.</li><li><strong>Reference</strong> contains the Data Dictionary, Source Standards and Units of Measure.</li><li><strong>Model, Intelligence, Contract and Quality</strong> provide the Data Model, AI Assistant, CIS Builder and Validation workspace.</li></ul><div className="guide-callout"><Search size={17}/><span>Global cross-domain search is planned but is <strong>not enabled in this pilot</strong>. Use the page-specific search and filter controls, or ask the AI Assistant for help locating relevant CFIHOS concepts.</span></div></GuideSection>

        <GuideSection id="classes" title="Tag Classes & Equipment Classes"><p>Use <Link to="/classes/tag">Tag Classes</Link> and <Link to="/classes/equipment">Equipment Classes</Link> to browse CFIHOS class definitions, properties and relationships. Select a class to inspect its CFIHOS ID, definition, property requirements, related classes, document requirements and source-standard provenance where available.</p><p>Class pages are particularly useful before defining CIS scope because they show what information CFIHOS associates with a real asset class.</p></GuideSection>

        <GuideSection id="information" title="Documents, disciplines & lifecycle requirements"><p><Link to="/documents">Document Types</Link> describes CFIHOS deliverable types. <Link to="/disciplines">Disciplines</Link> provides engineering discipline reference data. <Link to="/lifecycle">Lifecycle Requirements</Link> shows document status expectations by lifecycle phase and discipline.</p><p>Lifecycle tables can be sorted so you can review requirements by document, discipline, phase or required status.</p></GuideSection>

        <GuideSection id="reference" title="Data Dictionary, standards & units"><p>The <Link to="/dictionary">Data Dictionary</Link> is the primary property reference. Use <Link to="/standards">Source Standards</Link> to trace external or CFIHOS standards, and <Link to="/units">Units of Measure</Link> to inspect dimensional/unit reference data.</p></GuideSection>

        <GuideSection id="model" title="Data Model"><p>The <Link to="/model">Data Model</Link> provides a structural view of the CFIHOS reference-data model. Use it when you need to understand how classes, properties, documents, standards and other objects fit together rather than inspecting one record at a time.</p></GuideSection>

        <GuideSection id="validation" title="Validation"><p>The <Link to="/validation">Validation</Link> workspace presents reproducible checks against the CFIHOS 2.0 source data. It separates validated areas, upstream-review findings and engineering observations so reviewers can understand both what is confirmed and what still needs interpretation.</p><div className="guide-callout"><CheckCircle2 size={17}/><span>Validation is evidence-oriented: use expandable results and diagnostics to understand why a check passed or why an upstream issue remains open.</span></div></GuideSection>

        <GuideSection id="cis" title="CIS Builder"><p>The <Link to="/cis">Contract Information Specification Builder</Link> turns selected CFIHOS scope into a traceable contractual baseline.</p><div className="guide-steps"><div><b>1</b><strong>Scope</strong><span>Define project/package details, classes and disciplines.</span></div><div><b>2</b><strong>Baseline review</strong><span>Review CFIHOS asset data, documents, standards and lifecycle obligations.</span></div><div><b>3</b><strong>Overrides</strong><span>Record explicit Owner/Operator exclusions, changes or additions with rationale.</span></div><div><b>4</b><strong>Export</strong><span>Review the final contract and create structured outputs.</span></div></div><p>The governing concept is <strong>CFIHOS baseline + explicit Owner/Operator deviations = Contract CIS</strong>. Overrides never silently mutate the locked baseline.</p><div className="guide-format-grid"><div><FileJson size={20}/><strong>JSON — recommended editable master</strong><span>Use Save CIS / Open CIS while developing and governing the specification. JSON preserves scope, baseline, provenance and overrides.</span></div><div><FileSpreadsheet size={20}/><strong>CSV — issue / exchange</strong><span>Use primarily for EPC spreadsheet exchange and downstream execution. Builder-generated CSV supports controlled re-import.</span></div></div></GuideSection>

        <GuideSection id="assistant" title="AI Assistant"><p>The <Link to="/assistant">CFIHOS Assistant</Link> retrieves evidence before generative synthesis. It can answer direct CFIHOS questions, interpret ambiguous CFIHOS terminology and explain known Explorer capabilities.</p><div className="guide-status-grid"><div><strong>Grounded</strong><span>Direct or resolved CFIHOS evidence supports the answer.</span></div><div><strong>Interpreted</strong><span>AI interpretation of retrieved evidence; verify against the evidence cards.</span></div><div><strong>Needs interpretation</strong><span>Candidate evidence exists but generative synthesis is unavailable.</span></div><div><strong>Insufficient evidence</strong><span>The retriever found no CFIHOS or Explorer capability evidence to support a reliable answer.</span></div></div><p>The Assistant sends the user question and bounded retrieved evidence to a server-side model endpoint. The OpenAI API key stays server-side, response storage is disabled by the application request, and the model has no direct access to the raw workbook or public web. AI output can still be wrong: evidence cards are the verification layer.</p><p>Application actions such as <em>Open CIS Builder</em> use deterministic routes rather than model-generated URLs.</p></GuideSection>

        <GuideSection id="workflows" title="Common workflows"><div className="workflow-list"><div><strong>Understand an asset class</strong><span>Search Tag/Equipment Classes → inspect properties and documents → follow standards/provenance.</span></div><div><strong>Review document expectations</strong><span>Open a class → review Required Documents → inspect Lifecycle Requirements for phase/status expectations.</span></div><div><strong>Create a project CIS</strong><span>Open CIS Builder → define scope → generate baseline → review → record overrides → save JSON → export CSV when required.</span></div><div><strong>Investigate a question</strong><span>Ask AI Assistant → read the answer → verify evidence cards → follow the suggested Explorer action.</span></div></div></GuideSection>

        <GuideSection id="feedback" title="Pilot feedback"><p>Feedback from pilot users is part of the evaluation. Please include the page or workflow you were using, what you expected, what happened, and—where appropriate—the CFIHOS identifier involved. Do not include confidential project information, credentials or API keys in feedback emails.</p><a className="guide-feedback-link" href={`mailto:${PILOT_FEEDBACK_EMAIL}?subject=CFIHOS%20Explorer%20pilot%20feedback`}><Mail size={16}/>Email pilot feedback</a></GuideSection>

        <footer className="guide-footer"><span>Need context on the application itself?</span><Link to="/about">About CFIHOS Explorer <ArrowRight size={15}/></Link></footer>
      </article>
    </div>
  );
}
