import { BellRing, CheckCircle2, Download, PlugZap, ShieldCheck } from "lucide-react";
import { useEffect,useState } from "react";
import { CONSUMER_INTEGRATION_DEMO_NOTIFICATIONS,CONSUMER_INTEGRATION_DEMO_SUBSCRIPTIONS } from "../rdl/consumerIntegrationDemo";
import { loadConsumerInbox,loadConsumerIntegrationSession,type ConsumerIntegrationSession,type ConsumerNotification,type ConsumerSubscription } from "../rdl/consumerIntegrationService";

export function RdlConsumerIntegrationPage(){
  const [session,setSession]=useState<ConsumerIntegrationSession|null>(null);const [subscriptions,setSubscriptions]=useState<ConsumerSubscription[]>(CONSUMER_INTEGRATION_DEMO_SUBSCRIPTIONS);const [notifications,setNotifications]=useState<ConsumerNotification[]>(CONSUMER_INTEGRATION_DEMO_NOTIFICATIONS);const [live,setLive]=useState(false);
  useEffect(()=>{let active=true;(async()=>{const s=await loadConsumerIntegrationSession();if(!active)return;setSession(s);if(!s)return;try{const payload=await loadConsumerInbox();if(active){setSubscriptions(payload.subscriptions);setNotifications(payload.notifications);setLive(true);}}catch{if(active){setSession(null);setSubscriptions(CONSUMER_INTEGRATION_DEMO_SUBSCRIPTIONS);setNotifications(CONSUMER_INTEGRATION_DEMO_NOTIFICATIONS);setLive(false);}}})();return()=>{active=false};},[]);
  return <div className="page rdl-hierarchy-page">
    <header className="page-header"><div><span className="eyebrow">RDL-020 · Consumer integration</span><h1>Consumer integration & change notification</h1><p>Notify downstream consumers that an immutable release exists, then let each consumer pull, verify, stage and explicitly activate its own pinned package.</p></div></header>
    <section className="rdl-hierarchy-callout" aria-labelledby="integration-boundary-heading"><ShieldCheck size={24}/><div><h2 id="integration-boundary-heading">Notify, pull, stage, activate</h2><p>{session&&live?`Authenticated package consumer: ${session.consumer}`:"Read-only integration demonstration"}. Notification never transfers mutable standards state and never auto-activates a release.</p></div></section>
    <section className="rdl-hierarchy-section" aria-labelledby="flow-heading"><h2 id="flow-heading">Explicit consumer lifecycle</h2><div className="rdl-publication-summary-grid"><article><BellRing/><strong>1. Notify</strong><span>A transactional event announces an exact published release.</span></article><article><Download/><strong>2. Pull & verify</strong><span>The consumer retrieves the pinned package and verifies SHA-256 integrity.</span></article><article><PlugZap/><strong>3. Stage</strong><span>The release enters the consumer staging area using an idempotent request key.</span></article><article><CheckCircle2/><strong>4. Activate</strong><span>Activation is an explicit consumer decision after review; it is never automatic.</span></article></div></section>
    <section className="rdl-hierarchy-section" aria-labelledby="subscription-heading"><h2 id="subscription-heading">Consumer subscriptions</h2><p className="rdl-intelligence-copy">Subscriptions describe which release contexts a consumer wants to discover. The current implementation supports pull-first consumption and defines a webhook contract without requiring webhook delivery in this sprint.</p><div className="rdl-governance-list">{subscriptions.map(s=><article className="rdl-governance-card" key={s.subscriptionId}><div><small>{s.consumerKey}</small><h3>{s.contextKey??"All published contexts"}</h3><p>Mode: {s.notificationMode} · Contract: {s.contractVersion}</p></div></article>)}</div></section>
    <section className="rdl-hierarchy-section" aria-labelledby="inbox-heading"><h2 id="inbox-heading">Release inbox</h2><p className="rdl-intelligence-copy">{live?"Live notifications from the governed consumer integration API are shown below.":"Demonstration notification only. Live acknowledgement, staging and activation remain fail-closed until a trusted consumer identity is available."}</p><div className="rdl-governance-list">{notifications.map(n=><article className="rdl-governance-card" key={n.notificationId}><div><small>{n.eventType} · {n.changeClassification}</small><h3>{n.releaseKey} · {n.releaseVersion}</h3><p>{n.contextName} · state: <strong>{n.consumerLifecycleStatus}</strong></p><code>{n.compositionSha256}</code></div><div className="rdl-publication-actions"><button type="button" disabled={!live||Boolean(n.acknowledgedAt)}>Acknowledge</button><button type="button" disabled={!live||n.consumerLifecycleStatus!=="discovered"}>Stage package</button><button type="button" disabled={!live||n.consumerLifecycleStatus!=="staged"}>Activate release</button></div></article>)}</div></section>
    <section className="rdl-hierarchy-section" aria-labelledby="idempotency-heading"><h2 id="idempotency-heading">Idempotent pull contract</h2><p className="rdl-intelligence-copy">Consumers send a stable request key when staging a release. Repeating the same request key does not create a second pull receipt. The release identifier and SHA-256 remain explicit so retries cannot silently select a different standard.</p></section>
    <section className="rdl-hierarchy-section" aria-labelledby="datagate-integration-heading"><h2 id="datagate-integration-heading">DataGate reference boundary</h2><p className="rdl-intelligence-copy">The reference pattern is push notification, pull content: RDL Explorer publishes and announces an immutable package; DataGate discovers it, verifies integrity, stages it for review and activates it according to DataGate governance. There is no direct SQL coupling and no automatic downstream activation.</p></section>
  </div>;
}
