import { Download, FileJson2, Fingerprint, PackageCheck, ShieldCheck } from "lucide-react";
import { useEffect,useState } from "react";
import { DISTRIBUTION_DEMO_RELEASES } from "../rdl/packageDistributionDemo";
import { distributionEntitiesUrl,distributionManifestUrl,distributionPackageUrl,loadDistributionCatalogue,loadDistributionSession,type DistributedRelease,type DistributionSession } from "../rdl/packageDistributionService";
export function RdlDistributionPage(){
  const [session,setSession]=useState<DistributionSession|null>(null);const [releases,setReleases]=useState<DistributedRelease[]>(DISTRIBUTION_DEMO_RELEASES);const [live,setLive]=useState(false);
  useEffect(()=>{let active=true;(async()=>{const s=await loadDistributionSession();if(!active)return;setSession(s);if(!s)return;try{const r=await loadDistributionCatalogue();if(active){setReleases(r);setLive(true);}}catch{if(active){setSession(null);setReleases(DISTRIBUTION_DEMO_RELEASES);setLive(false);}}})();return()=>{active=false};},[]);
  return <div className="page rdl-hierarchy-page">
    <header className="page-header"><div><span className="eyebrow">Distribution</span><h1>Published package distribution & consumption</h1><p>Consume immutable effective-standard releases through a stable, versioned, provenance-aware API without direct database coupling.</p></div></header>
    <section className="rdl-hierarchy-callout" aria-labelledby="distribution-boundary-heading"><ShieldCheck size={24}/><div><h2 id="distribution-boundary-heading">Consumption boundary</h2><p>{session&&live?`Authenticated package consumer: ${session.consumer}`:"Read-only distribution demonstration"}. Published package content is immutable. Consumer access is authorized server-side with the dedicated <code>rdl-package-consumer</code> role.</p></div></section>
    <section className="rdl-hierarchy-section" aria-labelledby="contract-heading"><h2 id="contract-heading">Stable consumer contract</h2><div className="rdl-publication-summary-grid"><article><PackageCheck/><strong>Release catalogue</strong><span>Discover exact published versions and lifecycle state.</span></article><article><FileJson2/><strong>Manifest & entities</strong><span>Read package lineage, compatibility metadata and effective entities.</span></article><article><Fingerprint/><strong>Integrity</strong><span>Verify SHA-256 fingerprints and pin an exact release.</span></article><article><Download/><strong>Immutable package</strong><span>Retrieve <code>rdl-distribution-package/v1</code> JSON for downstream systems.</span></article></div></section>
    <section className="rdl-hierarchy-section" aria-labelledby="catalogue-heading"><h2 id="catalogue-heading">Published release catalogue</h2><p className="rdl-intelligence-copy">{live?"Live releases from the governed distribution API are shown below.":"Demonstration release only. Live package endpoints remain fail-closed until a trusted consumer identity is available."}</p><div className="rdl-governance-list">{releases.map(r=><article className="rdl-governance-card" key={r.releaseId}><div><small>{r.contextName}</small><h3>{r.releaseKey} · {r.releaseVersion}</h3><p><span className={`rdl-review-status rdl-review-status-${r.lifecycleStatus==="active"?"approved":"retired"}`}>{r.lifecycleStatus}</span></p><code>{r.compositionSha256}</code><p>Compatibility: {String(r.compatibility.minimumConsumerVersion??"1.0")}+</p>{r.deprecationMessage&&<p>{r.deprecationMessage}</p>}</div><div className="rdl-publication-actions"><a href={live?distributionManifestUrl(r.releaseId):undefined} aria-disabled={!live} onClick={e=>{if(!live)e.preventDefault();}}>Manifest</a><a href={live?distributionEntitiesUrl(r.releaseId):undefined} aria-disabled={!live} onClick={e=>{if(!live)e.preventDefault();}}>Entities</a><a className="rdl-publication-download" href={live?distributionPackageUrl(r.releaseId):undefined} aria-disabled={!live} onClick={e=>{if(!live)e.preventDefault();}}><Download size={16}/>Package</a></div></article>)}</div></section>
    <section className="rdl-hierarchy-section" aria-labelledby="lifecycle-heading"><h2 id="lifecycle-heading">Deprecation and supersession</h2><p className="rdl-intelligence-copy">Consumers pin a release identifier and never follow “latest” implicitly. An immutable release can be marked deprecated or superseded through separate distribution metadata; its package bytes and composition fingerprint are never rewritten. A superseding release is an explicit new release.</p></section>
    <section className="rdl-hierarchy-section" aria-labelledby="datagate-heading"><h2 id="datagate-heading">Downstream integration boundary</h2><p className="rdl-intelligence-copy">The distribution contract is suitable for DataGate and engineering applications to discover, review, pin and retrieve a package. Activation remains the consumer's decision; no downstream system receives direct SQL access to RDL Explorer.</p></section>
  </div>;
}
