import { AlertTriangle, CheckCircle2, GitBranch, LockKeyhole, Plus, ShieldCheck, UserCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { EXTENSION_DEMO_ITEMS } from "../rdl/enterpriseExtensionsDemo";
import { createExtension, loadExtensionPreview, loadExtensionQueue, loadExtensionSession, promoteExtension, reviewExtension, type ExtensionItem, type ExtensionPreview, type ExtensionSession } from "../rdl/enterpriseExtensionService";

export function RdlExtensionsPage(){
  const [session,setSession]=useState<ExtensionSession|null>(); const [live,setLive]=useState<ExtensionItem[]>(); const [status,setStatus]=useState("in_review");
  const [editor,setEditor]=useState(false); const [active,setActive]=useState<ExtensionItem>(); const [preview,setPreview]=useState<ExtensionPreview>(); const [feedback,setFeedback]=useState("");
  const [form,setForm]=useState({contextKey:"DEMO-COMPANY",changeKind:"add",entityType:"equipment_class",nativeIdentifier:"",baseEntityId:"",proposedName:"",rationale:""});
  useEffect(()=>{loadExtensionSession().then(setSession).catch(()=>setSession(null));},[]);
  useEffect(()=>{if(!session){setLive(undefined);return;}loadExtensionQueue(status).then(setLive).catch(()=>setLive(undefined));},[session,status]);
  const items=useMemo(()=>live??EXTENSION_DEMO_ITEMS.filter(i=>status==="all"||i.status===status),[live,status]);
  async function openPreview(item:ExtensionItem){setActive(item);setFeedback("");if(session){try{setPreview(await loadExtensionPreview(item.extensionChangeId));}catch(e){setFeedback(e instanceof Error?e.message:"Preview failed.");}}else setPreview(undefined);}
  async function act(item:ExtensionItem,action:"submit"|"approve"|"reject"|"retire"){if(!session)return;const rationale=window.prompt(`Rationale for ${action} (minimum 10 characters)`);if(!rationale)return;try{await reviewExtension({extensionChangeId:item.extensionChangeId,action,rationale,expectedVersion:item.reviewVersion});setFeedback(`${action} decision recorded.`);setActive(undefined);setPreview(undefined);setLive(await loadExtensionQueue(status));}catch(e){setFeedback(e instanceof Error?e.message:"Governance action failed.");}}
  async function promote(item:ExtensionItem){if(!session)return;const targetContextKey=window.prompt("Target parent context key (Project → Asset or Asset → Company)");if(!targetContextKey)return;const rationale=window.prompt("Promotion rationale (minimum 10 characters)");if(!rationale)return;try{await promoteExtension({extensionChangeId:item.extensionChangeId,targetContextKey,rationale});setFeedback("Promotion draft created in the parent layer.");}catch(e){setFeedback(e instanceof Error?e.message:"Promotion failed.");}}
  async function create(){if(!session)return;try{await createExtension({...form,baseEntityId:form.changeKind==="add"?undefined:Number(form.baseEntityId)||undefined});setFeedback("Draft extension created.");setEditor(false);setLive(await loadExtensionQueue(status));}catch(e){setFeedback(e instanceof Error?e.message:"Draft creation failed.");}}
  return <div className="content-page rdl-extensions-page">
    <div className="page-heading"><div><span className="eyebrow">Enterprise standards</span><h1>Extension authoring & governance</h1></div><p>Author controlled Company, Asset and Project/CIS changes, review conflicts, preview the effective result and approve without mutating the inherited baseline.</p></div>
    <div className="rdl-intelligence-warning"><ShieldCheck size={20}/><div><strong>Governed authoring boundary</strong><p>Live writes require the signed <code>rdl-extension-reviewer</code> role. Without a trusted session this page uses clearly labelled demonstration records and remains read-only.</p></div></div>
    <div className={`rdl-governance-session ${session?"rdl-governance-session-live":""}`} role="status">{session?<><UserCheck size={18}/><div><strong>Authenticated extension reviewer</strong><span>{session.reviewer} · live authoring enabled</span></div></>:<><LockKeyhole size={18}/><div><strong>Read-only demonstration mode</strong><span>No trusted extension-governance identity is present.</span></div></>}</div>
    <section className="rdl-hierarchy-section" aria-labelledby="extension-workflow-heading"><h2 id="extension-workflow-heading">Controlled extension lifecycle</h2><div className="rdl-extension-flow"><span><Plus size={16}/>Draft</span><b>→</b><span><GitBranch size={16}/>In review</span><b>→</b><span><AlertTriangle size={16}/>Conflict check</span><b>→</b><span><CheckCircle2 size={16}/>Approved</span><b>→</b><span>Publish immutable effective context</span></div><p className="rdl-intelligence-copy">Approval is blocked when the same typed native identifier already has an unresolved extension in the selected context lineage. Promotion creates a new governed record at the target layer; it never rewrites the frozen project baseline.</p></section>
    <div className="rdl-governance-toolbar"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="in_review">In review</option><option value="draft">Draft</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="retired">Retired</option><option value="all">All</option></select></label><span>{items.length} extension records · {live?"live repository":"demonstration"}</span><button type="button" disabled={!session} onClick={()=>setEditor(v=>!v)}>New extension</button></div>
    {editor&&<div className="rdl-review-editor" aria-label="New enterprise extension"><strong>Author extension draft</strong><label>Context key<input value={form.contextKey} onChange={e=>setForm({...form,contextKey:e.target.value})}/></label><label>Change kind<select value={form.changeKind} onChange={e=>setForm({...form,changeKind:e.target.value})}><option value="add">Add</option><option value="override">Override</option><option value="retire">Retire</option></select></label><label>Entity type<input value={form.entityType} onChange={e=>setForm({...form,entityType:e.target.value})}/></label><label>Native identifier<input value={form.nativeIdentifier} onChange={e=>setForm({...form,nativeIdentifier:e.target.value})}/></label>{form.changeKind!=="add"&&<label>Base entity ID<input type="number" min="1" value={form.baseEntityId} onChange={e=>setForm({...form,baseEntityId:e.target.value})}/></label>}<label>Proposed name<input value={form.proposedName} onChange={e=>setForm({...form,proposedName:e.target.value})}/></label><label>Rationale<textarea rows={3} value={form.rationale} onChange={e=>setForm({...form,rationale:e.target.value})}/></label><div><button type="button" onClick={create}>Create draft</button><button type="button" onClick={()=>setEditor(false)}>Cancel</button></div></div>}
    {feedback&&<div role="status" className="rdl-governance-feedback">{feedback}</div>}
    <div className="rdl-governance-list">{items.map(item=><article className="rdl-governance-card" key={item.extensionChangeId}><div className="rdl-governance-card-head"><span className="rdl-mapping-type">{item.changeKind}</span><span className={`rdl-review-status rdl-review-status-${item.status}`}>{item.status.replaceAll("_"," ")}</span><span>v{item.reviewVersion}</span></div><div><small>{item.contextType} · {item.contextKey}</small><h3>{item.proposedName??item.nativeIdentifier}</h3><code>{item.entityType} · {item.nativeIdentifier}</code><p>{item.rationale}</p></div><div className="rdl-review-actions"><button type="button" onClick={()=>openPreview(item)}>Effective preview</button><button type="button" disabled={!session||!(item.status==="draft"||item.status==="candidate"||item.status==="rejected")} onClick={()=>void act(item,"submit")}>Submit</button><button type="button" disabled={!session||item.status!=="in_review"} onClick={()=>void act(item,"approve")}>Approve</button><button type="button" disabled={!session||item.status!=="in_review"} onClick={()=>void act(item,"reject")}>Reject</button><button type="button" disabled={!session||item.status!=="approved"||item.contextType==="company"} onClick={()=>void promote(item)}>Promote upward</button></div></article>)}</div>
    {active&&<section className="rdl-hierarchy-section" aria-labelledby="preview-heading"><h2 id="preview-heading">Effective preview</h2>{preview?<><p><strong>Effective result:</strong> {preview.effective.retired?"Retired in this context":preview.effective.name??active.proposedName}</p><p><strong>Conflicts:</strong> {preview.conflicts.length}</p><p><strong>Publishable:</strong> {preview.publishable?"Yes — approved and conflict-free":"No — resolve workflow/conflicts first"}</p></>:<p className="rdl-intelligence-copy">Demonstration preview: the proposed {active.changeKind} would be applied only in {active.contextKey}; the inherited upstream package remains unchanged.</p>}</section>}
  </div>;
}
