import { CheckCircle2, ClipboardCheck, LockKeyhole, Route, ShieldCheck, TriangleAlert } from "lucide-react";
import { useEffect, useState } from "react";
import { MIGRATION_PLAN_DEMO } from "../rdl/migrationPlanningDemo";
import { loadMigrationPlanningSession, type MigrationPlanningSession } from "../rdl/migrationPlanningService";

export function RdlMigrationPlanningPage(){
  const [session,setSession]=useState<MigrationPlanningSession|null>(null);
  const plan=MIGRATION_PLAN_DEMO;
  useEffect(()=>{let active=true;loadMigrationPlanningSession().then(v=>active&&setSession(v));return()=>{active=false};},[]);
  const complete=plan.actions.filter(a=>a.status==="completed"||a.status==="waived").length;
  return <div className="page rdl-hierarchy-page">
    <header className="page-header"><div><span className="eyebrow">RDL-022 · Controlled adoption</span><h1>Migration planning & controlled adoption</h1><p>Turn release impact intelligence into an owned remediation plan, prove readiness, pass an approval gate, stage the target release and activate it only through an explicit adoption decision.</p></div></header>
    <section className="rdl-hierarchy-callout" aria-labelledby="migration-boundary-heading"><LockKeyhole size={24}/><div><h2 id="migration-boundary-heading">Controlled adoption boundary</h2><p>{session?`Authenticated consumer: ${session.consumer}`:"Read-only migration demonstration"}. A published release or impact result never migrates a project or consumer automatically.</p></div></section>
    <section className="rdl-hierarchy-section" aria-labelledby="plan-heading"><h2 id="plan-heading">Migration plan</h2><div className="rdl-publication-summary-grid"><article><Route/><strong>{plan.fromRelease.version} → {plan.toRelease.version}</strong><span>{plan.subjectKey}</span></article><article><ClipboardCheck/><strong>{complete} / {plan.actions.length} actions closed</strong><span>Readiness: {plan.readiness.replace("_"," ")}</span></article><article><ShieldCheck/><strong>{plan.status.replace("_"," ")}</strong><span>Owner: {plan.ownerKey}</span></article></div><h3>{plan.title}</h3><p className="rdl-intelligence-copy">{plan.rationale}</p></section>
    <section className="rdl-hierarchy-section" aria-labelledby="actions-heading"><h2 id="actions-heading">Impacted entity checklist</h2><div className="rdl-table-scroll" tabIndex={0} aria-label="Migration remediation checklist"><table><thead><tr><th>Impact</th><th>Remediation action</th><th>Owner</th><th>Due</th><th>Status</th></tr></thead><tbody>{plan.actions.map(action=><tr key={action.id}><th scope="row">{action.entityType}<br/><code>{action.nativeIdentifier}</code>{action.breaking&&<><br/><span>Potentially breaking</span></>}</th><td>{action.actionText}</td><td>{action.ownerKey??"Unassigned"}</td><td>{action.dueDate??"—"}</td><td>{action.status.replace("_"," ")}</td></tr>)}</tbody></table></div></section>
    <section className="rdl-hierarchy-section" aria-labelledby="gate-heading"><h2 id="gate-heading">Approval gate</h2><p className="rdl-intelligence-copy">Approval is separate from readiness. Staging is blocked until the plan is approved, readiness is <strong>ready</strong>, and every remediation action is completed or explicitly waived with evidence.</p><div className="rdl-publication-actions"><button type="button" disabled={!session?.canApprove}>Approve migration plan</button><button type="button" disabled={!session}>Mark ready</button><button type="button" disabled={!session}>Stage target release</button></div></section>
    <section className="rdl-hierarchy-section" aria-labelledby="activation-heading"><h2 id="activation-heading">Explicit activation only</h2><div className="rdl-hierarchy-callout"><TriangleAlert size={22}/><div><p>A plan must move through <strong>draft → in review → approved → staged → activated</strong>. Activation cannot skip staging and remains a deliberate governed decision.</p><button type="button" disabled={!session}>Activate target release</button></div></div></section>
    <section className="rdl-hierarchy-section" aria-labelledby="audit-heading"><h2 id="audit-heading">Migration audit history</h2><ol>{plan.history.map(event=><li key={event.id}><CheckCircle2 size={16}/> <strong>{event.eventType}</strong> · {event.actor}{event.rationale?` — ${event.rationale}`:""}</li>)}</ol></section>
  </div>;
}
