import { Download, LockKeyhole, ShieldCheck, UserCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { EFFECTIVE_PUBLICATION_DEMO } from "../rdl/effectivePublicationDemo";
import { loadPublicationComparison,loadPublicationSession,loadPublishedReleases,publicationPackageUrl,publishEffectiveStandard,type PublicationComparison,type PublicationSession,type PublishedRelease } from "../rdl/effectivePublicationService";

const FILTERS=["all","add","override","retire"] as const;
type Filter=(typeof FILTERS)[number];
export function RdlPublicationPage(){
  const [session,setSession]=useState<PublicationSession|null>(null);const [comparison,setComparison]=useState<PublicationComparison>(EFFECTIVE_PUBLICATION_DEMO);const [live,setLive]=useState(false);const [filter,setFilter]=useState<Filter>("all");const [releases,setReleases]=useState<PublishedRelease[]>([]);const [feedback,setFeedback]=useState("");const [releaseKey,setReleaseKey]=useState("PROJECT-ALPHA-RDL");const [releaseVersion,setReleaseVersion]=useState("1.0.0");
  useEffect(()=>{let active=true;(async()=>{const s=await loadPublicationSession();if(!active)return;setSession(s);if(!s)return;try{const c=await loadPublicationComparison("DEMO-PROJECT-ALPHA");if(!active)return;setComparison(c);setReleases(await loadPublishedReleases(c.contextKey));setLive(true);}catch{if(active){setComparison(EFFECTIVE_PUBLICATION_DEMO);setLive(false);}}})();return()=>{active=false};},[]);
  const items=useMemo(()=>comparison.items.filter(i=>filter==="all"||i.changeKind===filter),[comparison,filter]);
  async function publish(){if(!session||!live)return;try{const r=await publishEffectiveStandard({contextKey:comparison.contextKey,releaseKey,releaseVersion});setReleases(v=>[r,...v]);setFeedback(`Published ${r.releaseKey} ${r.releaseVersion}.`);}catch(e){setFeedback(e instanceof Error?e.message:"Publication failed.");}}
  return <div className="content-page rdl-publication-page">
    <div className="page-heading"><div><span className="eyebrow">Enterprise standards</span><h1>Effective standard comparison & publication</h1></div><p>Compare the governed effective context with its inherited baseline, review change impact, and publish a machine-consumable immutable standard package.</p></div>
    <div className="rdl-intelligence-warning"><ShieldCheck size={20}/><div><strong>Publication boundary</strong><p>Publication requires the trusted <code>rdl-extension-reviewer</code> role. A published release is immutable and retains its exact lineage, package pins, extension provenance and SHA-256 composition fingerprint.</p></div></div>
    <div className={`rdl-governance-session ${session&&live?"rdl-governance-session-live":""}`} role="status">{session&&live?<><UserCheck size={18}/><div><strong>Authenticated publisher</strong><span>{session.reviewer} · live publication enabled</span></div></>:<><LockKeyhole size={18}/><div><strong>Read-only demonstration mode</strong><span>No trusted publication session is available. Demonstration records are not authoritative enterprise standards.</span></div></>}</div>
    <section className="rdl-hierarchy-section" aria-labelledby="comparison-heading"><h2 id="comparison-heading">Change impact</h2><div className="rdl-publication-summary" aria-label="Effective standard change summary"><span><b>{comparison.summary.inherited}</b> inherited package pins</span><span><b>{comparison.summary.added}</b> added</span><span><b>{comparison.summary.overridden}</b> overridden</span><span><b>{comparison.summary.retired}</b> retired</span></div><p className="rdl-intelligence-copy">The parent baseline remains immutable. The publication package records only governed downstream effects and exact provenance needed to reproduce this effective context.</p></section>
    <section className="rdl-hierarchy-section" aria-labelledby="comparison-detail-heading"><div className="rdl-publication-heading-row"><h2 id="comparison-detail-heading">Parent vs proposed effective standard</h2><label>Show<select value={filter} onChange={e=>setFilter(e.target.value as Filter)}>{FILTERS.map(v=><option key={v} value={v}>{v==="all"?"All changes":v}</option>)}</select></label></div><div className="rdl-publication-table-wrap" tabIndex={0} aria-label="Effective standard comparison table"><table className="rdl-publication-table"><thead><tr><th scope="col">Change</th><th scope="col">Layer</th><th scope="col">Entity</th><th scope="col">Inherited</th><th scope="col">Effective</th></tr></thead><tbody>{items.map(i=><tr key={`${i.sourceLayer}-${i.entityType}-${i.nativeIdentifier}`}><td><span className={`rdl-review-status rdl-review-status-${i.changeKind==="retire"?"retired":"approved"}`}>{i.changeKind}</span></td><td>{i.sourceLayer}</td><td><strong>{i.nativeIdentifier}</strong><small>{i.entityType}</small></td><td>{i.inheritedName??"—"}</td><td>{i.changeKind==="retire"?<em>Retired in effective context</em>:i.effectiveName??"—"}</td></tr>)}</tbody></table></div></section>
    <section className="rdl-hierarchy-section" aria-labelledby="publication-heading"><h2 id="publication-heading">Publication candidate</h2><div className="rdl-publication-candidate"><div><ShieldCheck size={22}/><p><strong>{comparison.contextName}</strong><span>{comparison.contextKey} · {comparison.pendingCount===0?"No unresolved draft/review changes":"Pending governance changes remain"}</span></p></div><label>Release key<input value={releaseKey} onChange={e=>setReleaseKey(e.target.value)}/></label><label>Version<input value={releaseVersion} onChange={e=>setReleaseVersion(e.target.value)}/></label><button type="button" disabled={!session||!live||!comparison.publishable} onClick={()=>void publish()}><ShieldCheck size={17}/>Publish immutable package</button></div>{feedback&&<div role="status" className="rdl-governance-feedback">{feedback}</div>}</section>
    <section className="rdl-hierarchy-section" aria-labelledby="release-heading"><h2 id="release-heading">Published releases</h2>{releases.length===0?<p className="rdl-intelligence-copy">No live release is loaded in demonstration mode. In an authenticated environment, each published release is downloadable as a versioned JSON package containing its manifest, payload and composition SHA-256.</p>:<div className="rdl-governance-list">{releases.map(r=><article className="rdl-governance-card" key={r.releaseId}><div><small>{r.releaseKey}</small><h3>Version {r.releaseVersion}</h3><code>{r.compositionSha256}</code><p>Published by {r.publishedBy}</p></div><a className="rdl-publication-download" href={publicationPackageUrl(r.releaseId)}><Download size={16}/>Download package</a></article>)}</div>}</section>
  </div>;
}
