import { Building2, LockKeyhole, Settings2, ShieldCheck } from "lucide-react";
import { useEffect,useState } from "react";
import { ENTERPRISE_TENANT_DEMO } from "../rdl/enterpriseTenantDemo";
import { bindTenantResource,changeTenantConfiguration,changeTenantMember,changeTenantRole,loadAccessibleOrganizations,loadTenantAdminSummary,loadTenantSession,type TenantAdminSummary,type TenantOrganization,type TenantSession } from "../rdl/enterpriseTenantService";
import "./RdlTenantAdministrationPage.css";

export function RdlTenantAdministrationPage(){
  const[organizations,setOrganizations]=useState<TenantOrganization[]>([]);const[organizationKey,setOrganizationKey]=useState("");const[session,setSession]=useState<TenantSession|null>(null);const[live,setLive]=useState<TenantAdminSummary|null>(null);const[configKey,setConfigKey]=useState("default_release_channel");const[configValue,setConfigValue]=useState("controlled");const[resourceType,setResourceType]=useState("enterprise_context");const[resourceKey,setResourceKey]=useState("");const[memberSubject,setMemberSubject]=useState("");const[tenantRole,setTenantRole]=useState("rdl-extension-reviewer");const[rationale,setRationale]=useState("");const[message,setMessage]=useState("");
  async function discover(){const list=await loadAccessibleOrganizations();setOrganizations(list);setOrganizationKey(current=>current||list[0]?.organization_key||"")}
  async function refresh(key:string){if(!key){setSession(null);setLive(null);return}const[nextSession,nextSummary]=await Promise.all([loadTenantSession(key),loadTenantAdminSummary(key)]);setSession(nextSession);setLive(nextSession&&nextSummary?nextSummary:null)}
  useEffect(()=>{void discover()},[]);useEffect(()=>{void refresh(organizationKey)},[organizationKey]);
  const data=live??ENTERPRISE_TENANT_DEMO;const demo=!live;
  async function mutate(action:()=>Promise<unknown>,success:string){setMessage("");try{await action();setMessage(success);await refresh(organizationKey)}catch(error){setMessage(error instanceof Error?error.message:"Tenant administration request failed.")}}
  return <div className="tenant-admin-page">
    <header><div className="tenant-eyebrow"><Building2 size={16}/> RDL-028 · Tenant / Organization Isolation & Enterprise Configuration</div><h1>Organization isolation & configuration</h1><p>Establish explicit organization ownership for enterprise-private standards resources, resolve tenant membership and roles, and fail closed on cross-tenant access.</p></header>
    <section className={`tenant-mode ${demo?"demo":"live"}`}><ShieldCheck size={18}/><div><strong>{demo?"Read-only tenant demonstration":"Tenant-scoped enterprise session active"}</strong><span>{demo?"No live tenant data is exposed without trusted SSO, active organization membership and tenant authorization.":`Organization ${organizationKey} · ${session?.displayName}`}</span></div></section>
    {organizations.length>0&&<label className="tenant-selector">Active organization<select value={organizationKey} onChange={event=>setOrganizationKey(event.target.value)}>{organizations.map(item=><option key={item.organization_key} value={item.organization_key}>{item.display_name}</option>)}</select></label>}
    <section aria-labelledby="tenant-principles"><h2 id="tenant-principles">Isolation principles</h2><div className="tenant-principles"><article><LockKeyhole/><strong>Fail closed by membership</strong><span>An organization header is a selector, never authority. The server verifies active membership before returning tenant-private state.</span></article><article><Building2/><strong>One private owner</strong><span>Enterprise-private resources receive one organization binding. A request for the same resource through another organization is denied.</span></article><article><Settings2/><strong>Global RDL stays global</strong><span>Published industry/reference RDL can remain globally readable; company, asset, project and consumer state is tenant scoped.</span></article></div></section>
    <section aria-labelledby="portfolio-heading"><h2 id="portfolio-heading">Organization portfolio</h2><div className="tenant-grid">{data.organizations.map(item=><article className="tenant-card" key={item.organization_key}><strong>{item.display_name}</strong><span><code>{item.organization_key}</code> · {item.status}<br/>{item.active_members??0} active members · {item.bound_resources??0} bound resources</span></article>)}</div></section>
    {!demo&&<section aria-labelledby="tenant-admin-controls"><h2 id="tenant-admin-controls">Tenant configuration & resource binding</h2><div className="tenant-controls"><label>Configuration key<input value={configKey} onChange={e=>setConfigKey(e.target.value)}/></label><label>Configuration value<input value={configValue} onChange={e=>setConfigValue(e.target.value)}/></label><label>Resource type<select value={resourceType} onChange={e=>setResourceType(e.target.value)}>{data.resourceTypes.map(type=><option key={type}>{type}</option>)}</select></label><label>Resource key<input value={resourceKey} onChange={e=>setResourceKey(e.target.value)} placeholder="Immutable resource identifier"/></label><label>Member subject<input value={memberSubject} onChange={e=>setMemberSubject(e.target.value)} placeholder="Existing enterprise identity subject"/></label><label>Tenant role<input value={tenantRole} onChange={e=>setTenantRole(e.target.value)} placeholder="rdl-extension-reviewer"/></label><label>Audit rationale<input value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Required rationale"/></label><div><button type="button" onClick={()=>void mutate(()=>changeTenantConfiguration(organizationKey,{key:configKey,value:configValue,rationale}),"Configuration updated.")}>Save configuration</button> <button type="button" onClick={()=>void mutate(()=>bindTenantResource(organizationKey,{resourceType,resourceKey,rationale}),"Resource bound to organization.")}>Bind resource</button> <button type="button" onClick={()=>void mutate(()=>changeTenantMember(organizationKey,{action:"add",subject:memberSubject,rationale}),"Member added.")}>Add member</button> <button type="button" onClick={()=>void mutate(()=>changeTenantMember(organizationKey,{action:"remove",subject:memberSubject,rationale}),"Member removed.")}>Remove member</button> <button type="button" onClick={()=>void mutate(()=>changeTenantRole(organizationKey,{action:"assign",subject:memberSubject,role:tenantRole,rationale}),"Tenant role assigned.")}>Assign tenant role</button> <button type="button" onClick={()=>void mutate(()=>changeTenantRole(organizationKey,{action:"revoke",subject:memberSubject,role:tenantRole,rationale}),"Tenant role revoked.")}>Revoke tenant role</button></div></div>{message&&<p role="status" className="tenant-message">{message}</p>}</section>}
    <section aria-labelledby="members-heading"><h2 id="members-heading">Organization members</h2><div className="tenant-table" tabIndex={0} aria-label="Organization member directory"><table><thead><tr><th>User</th><th>Subject</th><th>Status</th><th>Source</th><th>Tenant roles</th></tr></thead><tbody>{data.members.length?data.members.map(member=><tr key={member.subject_key}><th scope="row">{member.display_name}<br/><small>{member.email}</small></th><td><code>{member.subject_key}</code></td><td>{member.status}</td><td>{member.membership_source}</td><td>{member.tenant_roles?.length?member.tenant_roles.join(", "):"None"}</td></tr>):<tr><td colSpan={5}>No organization members.</td></tr>}</tbody></table></div></section>
    <section aria-labelledby="bindings-heading"><h2 id="bindings-heading">Tenant-bound private resources</h2><div className="tenant-table" tabIndex={0} aria-label="Tenant-bound private resources"><table><thead><tr><th>Type</th><th>Resource</th><th>Bound by</th></tr></thead><tbody>{data.bindings.length?data.bindings.map(binding=><tr key={`${binding.resource_type}:${binding.resource_key}`}><th scope="row">{binding.resource_type}</th><td><code>{binding.resource_key}</code></td><td>{binding.bound_by}</td></tr>):<tr><td colSpan={3}>No private resources bound.</td></tr>}</tbody></table></div></section>
    <section className="tenant-boundary" aria-labelledby="tenant-boundary"><h2 id="tenant-boundary">Security boundary</h2><p><strong>Cross-tenant access is denied, not filtered after retrieval.</strong> Tenant-aware services establish organization membership before reading private state and assert resource ownership before a tenant-bound resource can be used.</p><p>RDL-028 establishes the reusable isolation contract. Existing global industry/reference browsing remains intentionally global; enterprise-private workflows can migrate onto this contract without changing the underlying industry RDL identity model.</p></section>
  </div>
}
