export type AiStandardsSession={authenticated:true;reviewer:string;roles:string[];authenticatedAt:string;contract:"rdl-ai-standards-intelligence/v1"};
export type AiEvidenceItem={id:string;kind:string;title:string;detail:string;source:"rdl"|"governance"|"application";authority:"direct"|"derived"|"candidate";route?:string};
export type AiEvidencePayload={schemaVersion:"rdl-ai-evidence/v1";generatedAt:string;intent:string;items:AiEvidenceItem[]};
export type AiAnswerPayload={schemaVersion:"rdl-ai-standards-intelligence/v1";advisory:true;intent:string;answer:string;model:string;promptVersion:string;evidence:AiEvidenceItem[];audit?:{advisory_key?:string;answer_sha256?:string}|null};
export async function loadAiStandardsSession():Promise<AiStandardsSession|null>{try{const v=await requestJson<unknown>("/api/ai-intelligence/session");return validSession(v)?v:null}catch{return null}}
export async function loadAiEvidence(question:string):Promise<AiEvidencePayload|null>{try{const v=await requestJson<unknown>(`/api/ai-intelligence/evidence?question=${encodeURIComponent(question)}`);return validEvidence(v)?v:null}catch{return null}}
export async function askAiStandards(question:string):Promise<AiAnswerPayload>{const v=await requestJson<unknown>("/api/ai-intelligence/ask",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})});if(!validAnswer(v))throw new Error("Invalid AI standards response.");return v}
function validSession(v:unknown):v is AiStandardsSession{if(!v||typeof v!=="object")return false;const o=v as Record<string,unknown>;return o.authenticated===true&&typeof o.reviewer==="string"&&o.reviewer.trim().length>0&&Array.isArray(o.roles)&&o.roles.every(x=>typeof x==="string")&&typeof o.authenticatedAt==="string"&&o.contract==="rdl-ai-standards-intelligence/v1"}
function validEvidence(v:unknown):v is AiEvidencePayload{if(!v||typeof v!=="object")return false;const o=v as Record<string,unknown>;return o.schemaVersion==="rdl-ai-evidence/v1"&&typeof o.generatedAt==="string"&&typeof o.intent==="string"&&Array.isArray(o.items)&&o.items.every(validItem)}
function validAnswer(v:unknown):v is AiAnswerPayload{if(!v||typeof v!=="object")return false;const o=v as Record<string,unknown>;return o.schemaVersion==="rdl-ai-standards-intelligence/v1"&&o.advisory===true&&typeof o.answer==="string"&&o.answer.trim().length>0&&typeof o.model==="string"&&typeof o.promptVersion==="string"&&o.promptVersion.trim().length>0&&Array.isArray(o.evidence)&&o.evidence.every(validItem)}
function validItem(v:unknown){if(!v||typeof v!=="object")return false;const o=v as Record<string,unknown>;return typeof o.id==="string"&&typeof o.kind==="string"&&typeof o.title==="string"&&typeof o.detail==="string"&&["rdl","governance","application"].includes(String(o.source))&&["direct","derived","candidate"].includes(String(o.authority))}
async function requestJson<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{Accept:"application/json",...(init?.headers||{})}});const ct=r.headers.get("content-type")?.toLowerCase()??"";if(!ct.includes("application/json"))throw new Error("Expected JSON response.");const p:unknown=await r.json();if(!r.ok){const m=p&&typeof p==="object"&&typeof (p as any).error==="string"?(p as any).error:"AI standards request failed.";throw new Error(m)}return p as T}
