export type AiTrustSession={authenticated:true;reviewer:string;roles:string[];authenticatedAt:string;contract:"rdl-ai-trust/v1"};
export type AiTrustMetrics={feedback_count:number;helpful_count:number;incorrect_count:number;incomplete_count:number;evidence_concern_count:number;evaluation_count:number;avg_groundedness_score:number;avg_evidence_coverage_score:number;unsupported_claim_count:number;pass_count:number;review_count:number;fail_count:number;helpful_rate:number};
export type AiTrustRun={advisory_key:string;actor_key:string;intent:string;model_key:string;prompt_version:string;evidence_item_count:number;created_at:string;feedback_count:number;helpful_count:number;incorrect_count:number;incomplete_count:number};
export type AiTrustEvaluation={result_key:string;case_key:string;case_version:number;model_key:string;prompt_version:string;groundedness_score:number;evidence_coverage_score:number;unsupported_claim_count:number;verdict:"pass"|"review"|"fail";evaluated_at:string};
export type AiTrustSummary={schemaVersion:"rdl-ai-trust/v1";generatedAt:string;metrics:AiTrustMetrics;recentRuns:AiTrustRun[];recentEvaluations:AiTrustEvaluation[]};
export type FeedbackClassification="helpful"|"incorrect"|"incomplete";

export async function loadAiTrustSession():Promise<AiTrustSession|null>{try{const v=await requestJson<unknown>("/api/ai-trust/session");return validSession(v)?v:null}catch{return null}}
export async function loadAiTrustSummary():Promise<AiTrustSummary|null>{try{const v=await requestJson<unknown>("/api/ai-trust/summary");return validSummary(v)?v:null}catch{return null}}
export async function submitAiFeedback(input:{advisoryKey:string;classification:FeedbackClassification;comment?:string;evidenceConcern?:boolean}){return requestJson<unknown>("/api/ai-trust/feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)})}

function validSession(v:unknown):v is AiTrustSession{if(!v||typeof v!=="object")return false;const o=v as Record<string,unknown>;return o.authenticated===true&&typeof o.reviewer==="string"&&o.reviewer.trim().length>0&&Array.isArray(o.roles)&&o.roles.every(x=>typeof x==="string")&&typeof o.authenticatedAt==="string"&&o.contract==="rdl-ai-trust/v1"}
function validSummary(v:unknown):v is AiTrustSummary{if(!v||typeof v!=="object")return false;const o=v as any;return o.schemaVersion==="rdl-ai-trust/v1"&&typeof o.generatedAt==="string"&&validMetrics(o.metrics)&&Array.isArray(o.recentRuns)&&o.recentRuns.every(validRun)&&Array.isArray(o.recentEvaluations)&&o.recentEvaluations.every(validEvaluation)}
function validMetrics(v:any){return v&&typeof v==="object"&&["feedback_count","helpful_count","incorrect_count","incomplete_count","evidence_concern_count","evaluation_count","unsupported_claim_count","pass_count","review_count","fail_count"].every(k=>Number.isFinite(Number(v[k])))&&Number.isFinite(Number(v.avg_groundedness_score))&&Number.isFinite(Number(v.avg_evidence_coverage_score))&&Number.isFinite(Number(v.helpful_rate))}
function validRun(v:any){return v&&typeof v.advisory_key==="string"&&typeof v.intent==="string"&&typeof v.model_key==="string"&&typeof v.prompt_version==="string"}
function validEvaluation(v:any){return v&&typeof v.result_key==="string"&&typeof v.case_key==="string"&&["pass","review","fail"].includes(v.verdict)}
async function requestJson<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{Accept:"application/json",...(init?.headers||{})}});const ct=r.headers.get("content-type")?.toLowerCase()??"";if(!ct.includes("application/json"))throw new Error("Expected JSON response.");const p:unknown=await r.json();if(!r.ok){const m=p&&typeof p==="object"&&typeof (p as any).error==="string"?(p as any).error:"AI trust request failed.";throw new Error(m)}return p as T}
