export type TenantOrganization={organization_key:string;display_name:string;status:"active"|"suspended";membership_status?:string;active_members?:number;bound_resources?:number};
export type TenantSession={authenticated:true;organizationKey:string;subject:string;email:string;displayName:string;globalRoles:string[];tenantRoles:string[];contract:"rdl-enterprise-tenant-session/v1"};
export type TenantAdminSummary={schemaVersion:"rdl-enterprise-tenant-admin/v1";generatedAt:string;organizationKey:string;organizations:TenantOrganization[];members:Array<{subject_key:string;email:string;display_name:string;status:string;membership_source:string;assigned_at:string;tenant_roles:string[]}>;configuration:Array<{config_key:string;config_value:unknown;updated_by:string;updated_at:string}>;bindings:Array<{resource_type:string;resource_key:string;bound_by:string;bound_at:string}>;resourceTypes:string[]};
export async function loadAccessibleOrganizations(){try{const value=await requestJson<unknown>("/api/tenant/organizations");if(!value||typeof value!=="object")return[];const o=value as any;return o.contract==="rdl-enterprise-organization-list/v1"&&Array.isArray(o.organizations)?o.organizations.filter(validOrganization):[]}catch{return[]}}
export async function loadTenantSession(organizationKey:string){try{const value=await tenantJson<unknown>(organizationKey,"/api/tenant/session");return validSession(value)?value:null}catch{return null}}
export async function loadTenantAdminSummary(organizationKey:string){try{const value=await tenantJson<unknown>(organizationKey,"/api/tenant/admin");return validSummary(value)?value:null}catch{return null}}
export function changeTenantMember(organizationKey:string,input:{action:"add"|"remove";subject:string;rationale:string}){return tenantJson(organizationKey,"/api/tenant/member",post(input))}
export function changeTenantRole(organizationKey:string,input:{action:"assign"|"revoke";subject:string;role:string;rationale:string}){return tenantJson(organizationKey,"/api/tenant/role",post(input))}
export function changeTenantConfiguration(organizationKey:string,input:{key:string;value:unknown;rationale:string}){return tenantJson(organizationKey,"/api/tenant/configuration",post(input))}
export function bindTenantResource(organizationKey:string,input:{resourceType:string;resourceKey:string;rationale:string}){return tenantJson(organizationKey,"/api/tenant/binding",post(input))}
function post(input:unknown):RequestInit{return{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)}}
function validOrganization(v:any){return v&&typeof v.organization_key==="string"&&typeof v.display_name==="string"&&["active","suspended"].includes(v.status)}
function validSession(v:unknown):v is TenantSession{if(!v||typeof v!=="object")return false;const o=v as any;return o.authenticated===true&&typeof o.organizationKey==="string"&&typeof o.subject==="string"&&typeof o.email==="string"&&typeof o.displayName==="string"&&Array.isArray(o.globalRoles)&&Array.isArray(o.tenantRoles)&&o.contract==="rdl-enterprise-tenant-session/v1"}
function validSummary(v:unknown):v is TenantAdminSummary{if(!v||typeof v!=="object")return false;const o=v as any;return o.schemaVersion==="rdl-enterprise-tenant-admin/v1"&&typeof o.organizationKey==="string"&&Array.isArray(o.organizations)&&Array.isArray(o.members)&&Array.isArray(o.configuration)&&Array.isArray(o.bindings)&&Array.isArray(o.resourceTypes)}
async function tenantJson<T=unknown>(organizationKey:string,url:string,init?:RequestInit):Promise<T>{return requestJson(url,{...init,headers:{"x-rdl-organization-key":organizationKey,...(init?.headers||{})}})}
async function requestJson<T=unknown>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,headers:{Accept:"application/json",...(init?.headers||{})}});const contentType=response.headers.get("content-type")?.toLowerCase()??"";if(!contentType.includes("application/json"))throw new Error("Expected JSON response.");const payload:unknown=await response.json();if(!response.ok){const message=payload&&typeof payload==="object"&&typeof (payload as any).error==="string"?(payload as any).error:"Enterprise tenant request failed.";throw new Error(message)}return payload as T}
