export type EnterpriseIdentitySession={authenticated:true;subject:string;email:string;displayName:string;groups:string[];roles:string[];status:"active"|"disabled";authenticatedAt:string;contract:"rdl-enterprise-identity/v1"};
export type IdentityDirectoryUser={subject_key:string;email:string;display_name:string;identity_provider:string;status:"active"|"disabled";last_authenticated_at:string|null;direct_roles:string[]};
export type IdentityAdminSummary={schemaVersion:"rdl-enterprise-identity-admin/v1";generatedAt:string;users:IdentityDirectoryUser[];groupMappings:Array<{group_key:string;role_key:string;status:string}>;availableRoles:string[]};
export async function loadEnterpriseIdentitySession(){try{const v=await requestJson<unknown>("/api/identity/session");return validSession(v)?v:null}catch{return null}}
export async function loadIdentityAdminSummary(){try{const v=await requestJson<unknown>("/api/identity/admin");return validSummary(v)?v:null}catch{return null}}
export async function changeDirectRole(input:{action:"assign"|"revoke";subject:string;role:string;rationale:string}){return requestJson("/api/identity/role",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)})}
export async function changeUserStatus(input:{subject:string;status:"active"|"disabled";rationale:string}){return requestJson("/api/identity/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)})}
export async function changeGroupMapping(input:{action:"create"|"disable";group:string;role:string;rationale:string}){return requestJson("/api/identity/group-mapping",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)})}
function validSession(v:unknown):v is EnterpriseIdentitySession{if(!v||typeof v!=="object")return false;const o=v as any;return o.authenticated===true&&typeof o.subject==="string"&&o.subject.trim()&&typeof o.email==="string"&&typeof o.displayName==="string"&&Array.isArray(o.groups)&&Array.isArray(o.roles)&&o.roles.every((x:unknown)=>typeof x==="string")&&["active","disabled"].includes(o.status)&&typeof o.authenticatedAt==="string"&&o.contract==="rdl-enterprise-identity/v1"}
function validSummary(v:unknown):v is IdentityAdminSummary{if(!v||typeof v!=="object")return false;const o=v as any;return o.schemaVersion==="rdl-enterprise-identity-admin/v1"&&typeof o.generatedAt==="string"&&Array.isArray(o.users)&&o.users.every((u:any)=>typeof u.subject_key==="string"&&typeof u.email==="string"&&Array.isArray(u.direct_roles))&&Array.isArray(o.groupMappings)&&Array.isArray(o.availableRoles)}
async function requestJson<T=unknown>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{Accept:"application/json",...(init?.headers||{})}});const ct=r.headers.get("content-type")?.toLowerCase()??"";if(!ct.includes("application/json"))throw new Error("Expected JSON response.");const p:unknown=await r.json();if(!r.ok){const m=p&&typeof p==="object"&&typeof (p as any).error==="string"?(p as any).error:"Enterprise identity request failed.";throw new Error(m)}return p as T}
