export type MigrationPlanningSession={authenticated:true;consumer:string;roles:string[];authenticatedAt:string;contract:"rdl-migration-planning/v1";canApprove:boolean};
export type MigrationAction={id:number;actionKey:string;entityType?:string;nativeIdentifier?:string;changeKind?:"added"|"removed"|"modified"|"unchanged";breaking:boolean;actionText:string;ownerKey?:string;dueDate?:string;status:"open"|"in_progress"|"completed"|"waived";evidenceText?:string};
export type MigrationHistoryEvent={id:number;eventType:string;actor:string;fromStatus?:string;toStatus?:string;rationale?:string;createdAt:string};
export type MigrationPlan={id:number;subjectType:"consumer"|"project";subjectKey:string;title:string;rationale:string;ownerKey:string;dueDate?:string;readiness:"not_ready"|"in_progress"|"ready"|"blocked";status:"draft"|"in_review"|"approved"|"staged"|"activated"|"rejected"|"cancelled";expectedVersion:number;fromRelease:{key:string;version:string};toRelease:{key:string;version:string};actions:MigrationAction[];history:MigrationHistoryEvent[]};

export async function loadMigrationPlanningSession():Promise<MigrationPlanningSession|null>{try{const v=await json<unknown>("/api/adoption/session");return validSession(v)?v:null;}catch{return null;}}
export async function loadMigrationPlans():Promise<MigrationPlan[]>{const v=await json<{plans?:unknown}>("/api/adoption/plans");return Array.isArray(v.plans)?v.plans as MigrationPlan[]:[];}

function validSession(v:unknown):v is MigrationPlanningSession{if(!v||typeof v!=="object")return false;const o=v as Record<string,unknown>;return o.authenticated===true&&typeof o.consumer==="string"&&o.consumer.trim().length>0&&Array.isArray(o.roles)&&o.roles.every(r=>typeof r==="string")&&typeof o.authenticatedAt==="string"&&o.authenticatedAt.trim().length>0&&o.contract==="rdl-migration-planning/v1"&&typeof o.canApprove==="boolean";}
async function json<T>(url:string):Promise<T>{const r=await fetch(url,{headers:{Accept:"application/json"}});const ct=r.headers.get("content-type")?.toLowerCase()??"";if(!ct.includes("application/json"))throw new Error("Expected JSON response.");const p:unknown=await r.json();if(!r.ok)throw new Error(p&&typeof p==="object"&&typeof (p as Record<string,unknown>).error==="string"?String((p as Record<string,unknown>).error):"Migration planning request failed.");return p as T;}
