export type DistributionSession={authenticated:true;consumer:string;roles:string[];authenticatedAt:string;contract:"rdl-distribution/v1"};
export type DistributedRelease={releaseId:number;contextKey:string;contextType:string;contextName:string;releaseKey:string;releaseVersion:string;compositionSha256:string;publishedBy:string;publishedAt:string;lifecycleStatus:"active"|"deprecated"|"superseded";supersededByReleaseId?:number;compatibility:Record<string,unknown>;deprecationMessage?:string};
export async function loadDistributionSession():Promise<DistributionSession|null>{try{const payload=await requestJson<unknown>("/api/distribution/session");return isSession(payload)?payload:null;}catch{return null;}}
export async function loadDistributionCatalogue():Promise<DistributedRelease[]>{const payload=await requestJson<{releases:DistributedRelease[]}>("/api/distribution/catalogue");return Array.isArray(payload.releases)?payload.releases:[];}
export function distributionManifestUrl(releaseId:number){return `/api/distribution/manifest?id=${encodeURIComponent(String(releaseId))}`;}
export function distributionEntitiesUrl(releaseId:number){return `/api/distribution/entities?id=${encodeURIComponent(String(releaseId))}`;}
export function distributionPackageUrl(releaseId:number){return `/api/distribution/package?id=${encodeURIComponent(String(releaseId))}`;}
function isSession(value:unknown):value is DistributionSession{if(!value||typeof value!=="object")return false;const c=value as Record<string,unknown>;return c.authenticated===true&&typeof c.consumer==="string"&&c.consumer.trim().length>0&&Array.isArray(c.roles)&&c.roles.every(r=>typeof r==="string")&&typeof c.authenticatedAt==="string"&&c.authenticatedAt.trim().length>0&&c.contract==="rdl-distribution/v1";}
async function requestJson<T>(url:string):Promise<T>{const response=await fetch(url,{headers:{Accept:"application/json"}});const contentType=response.headers.get("content-type")?.toLowerCase()??"";if(!contentType.includes("application/json"))throw new Error(`Expected JSON response from ${url}.`);const payload:unknown=await response.json();if(!response.ok)throw new Error(payload&&typeof payload==="object"&&typeof (payload as Record<string,unknown>).error==="string"?String((payload as Record<string,unknown>).error):`Request failed (${response.status}).`);return payload as T;}
