import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

const SNAPSHOT_PATH = new URL(
  "../public/cfihos-workbook.json",
  import.meta.url,
);

const EXPECTED_SCHEMA = "cfihos-workbook-snapshot-v1";
const RELEASE_KEY = "cfihos-2.0";
const FIRST_DATA_ROW_NUMBER = 2;
const RECORD_BATCH_SIZE = 250;

type WorksheetRow = Record<string, unknown>;

type WorkbookSnapshot = {
  schema: string;
  source: {
    url: string;
    generatedAt: string;
    sha256: string;
  };
  sheetNames: string[];
  sheets: Record<
    string,
    {
      headers: string[];
      rows: WorksheetRow[];
    }
  >;
};

type SourceRecordStage = {
  sheetName: string;
  sourceRowNumber: number;
  recordOrder: number;
  rawRow: WorksheetRow;
  rowSha256: string;
};

function fail(message: string): never {
  throw new Error(`RDL-041.1 source-record generation failed: ${message}`);
}

function assertSnapshot(value: unknown): asserts value is WorkbookSnapshot {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    fail("snapshot root is not an object");
  }

  const candidate = value as Partial<WorkbookSnapshot>;

  if (candidate.schema !== EXPECTED_SCHEMA) {
    fail(`unexpected snapshot schema ${String(candidate.schema)}`);
  }

  if (!candidate.source || typeof candidate.source !== "object") {
    fail("source metadata is missing");
  }

  if (!/^[0-9a-f]{64}$/i.test(String(candidate.source.sha256 ?? ""))) {
    fail("source SHA-256 is missing or invalid");
  }

  if (!Array.isArray(candidate.sheetNames)) {
    fail("sheetNames is missing or invalid");
  }

  if (!candidate.sheets || typeof candidate.sheets !== "object") {
    fail("sheets is missing or invalid");
  }

  const uniqueNames = new Set(candidate.sheetNames);
  if (uniqueNames.size !== candidate.sheetNames.length) {
    fail("sheetNames contains duplicates");
  }

  const storedNames = Object.keys(candidate.sheets);
  if (
    storedNames.length !== candidate.sheetNames.length ||
    storedNames.some((name) => !uniqueNames.has(name))
  ) {
    fail("sheetNames and sheets keys differ");
  }

  for (const sheetName of candidate.sheetNames) {
    const sheet = candidate.sheets[sheetName];
    if (!sheet || !Array.isArray(sheet.headers) || !Array.isArray(sheet.rows)) {
      fail(`worksheet ${sheetName} has an invalid contract`);
    }

    if (!sheet.headers.every((header) => typeof header === "string")) {
      fail(`worksheet ${sheetName} contains a non-string header`);
    }

    if (
      !sheet.rows.every(
        (row) => row && typeof row === "object" && !Array.isArray(row),
      )
    ) {
      fail(`worksheet ${sheetName} contains a non-object row`);
    }
  }
}

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(canonicalize);
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
        .map(([key, item]) => [key, canonicalize(item)]),
    );
  }

  return value;
}

function canonicalJson(value: unknown): string {
  return JSON.stringify(canonicalize(value));
}

function sha256(value: unknown): string {
  return createHash("sha256").update(canonicalJson(value)).digest("hex");
}

function sqlText(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function jsonSql(value: unknown): string {
  return `${sqlText(JSON.stringify(value))}::jsonb`;
}

function emit(line = ""): void {
  process.stdout.write(`${line}\n`);
}

const parsed: unknown = JSON.parse(readFileSync(SNAPSHOT_PATH, "utf8"));
assertSnapshot(parsed);

const workbook = parsed;
const sourceSha256 = workbook.source.sha256.toLowerCase();
const packageKey = `cfihos-2.0-${sourceSha256.slice(0, 12)}`;
const sourceRecords: SourceRecordStage[] = [];

for (const sheetName of workbook.sheetNames) {
  const sheet = workbook.sheets[sheetName];

  sheet.rows.forEach((rawRow, recordOrder) => {
    sourceRecords.push({
      sheetName,
      sourceRowNumber: FIRST_DATA_ROW_NUMBER + recordOrder,
      recordOrder,
      rawRow,
      rowSha256: sha256(rawRow),
    });
  });
}

emit("-- Generated by scripts/generate-cfihos-source-record-sql.ts");
emit("-- RDL-041.1 lossless CFIHOS source-record ingestion.");
emit("BEGIN;");
emit("SET LOCAL standard_conforming_strings = on;");
emit(
  `SELECT pg_advisory_xact_lock(hashtext('rdl-041-source-records'), hashtext(${sqlText(packageKey)}));`,
);
emit();
emit("DO $rdl041_package$");
emit("DECLARE");
emit("  v_package_id bigint;");
emit("  v_content_sha256 text;");
emit("  v_release_key text;");
emit("BEGIN");
emit("  SELECT p.package_id, p.content_sha256, r.release_key");
emit("    INTO v_package_id, v_content_sha256, v_release_key");
emit("  FROM rdl.rdl_package p");
emit("  JOIN rdl.rdl_release r ON r.release_id = p.release_id");
emit("  JOIN rdl.rdl_source s ON s.source_id = r.source_id");
emit(`  WHERE p.package_key = ${sqlText(packageKey)}`);
emit("    AND s.source_key = 'cfihos';");
emit();
emit("  IF v_package_id IS NULL THEN");
emit(
  `    RAISE EXCEPTION 'Validated CFIHOS package ${packageKey} was not found' USING ERRCODE = '23503';`,
);
emit("  END IF;");
emit();
emit(`  IF v_release_key IS DISTINCT FROM ${sqlText(RELEASE_KEY)} THEN`);
emit(
  "    RAISE EXCEPTION 'Unexpected CFIHOS release key % for package %', v_release_key, v_package_id USING ERRCODE = '23514';",
);
emit("  END IF;");
emit();
emit(`  IF v_content_sha256 IS DISTINCT FROM ${sqlText(sourceSha256)} THEN`);
emit(
  "    RAISE EXCEPTION 'CFIHOS package fingerprint mismatch: expected %, actual %',",
);
emit(`      ${sqlText(sourceSha256)}, v_content_sha256 USING ERRCODE = '23514';`);
emit("  END IF;");
emit("END;");
emit("$rdl041_package$;");
emit();
emit("CREATE TEMP TABLE rdl041_source_sheet_stage (");
emit("  sheet_name text PRIMARY KEY,");
emit("  sheet_order integer NOT NULL UNIQUE,");
emit("  first_data_row_number integer NOT NULL,");
emit("  headers jsonb NOT NULL,");
emit("  source_row_count integer NOT NULL,");
emit("  sheet_sha256 text NOT NULL");
emit(") ON COMMIT DROP;");
emit();
emit("CREATE TEMP TABLE rdl041_source_record_stage (");
emit("  sheet_name text NOT NULL,");
emit("  source_row_number integer NOT NULL,");
emit("  record_order integer NOT NULL,");
emit("  raw_row jsonb NOT NULL,");
emit("  row_sha256 text NOT NULL,");
emit("  PRIMARY KEY (sheet_name, record_order),");
emit("  UNIQUE (sheet_name, source_row_number)");
emit(") ON COMMIT DROP;");
emit();

emit("INSERT INTO rdl041_source_sheet_stage (");
emit(
  "  sheet_name, sheet_order, first_data_row_number, headers, source_row_count, sheet_sha256",
);
emit(") VALUES");
emit(
  workbook.sheetNames
    .map((sheetName, sheetOrder) => {
      const sheet = workbook.sheets[sheetName];
      const sheetSha256 = sha256({ headers: sheet.headers, rows: sheet.rows });
      return `  (${sqlText(sheetName)}, ${sheetOrder}, ${FIRST_DATA_ROW_NUMBER}, ${jsonSql(sheet.headers)}, ${sheet.rows.length}, ${sqlText(sheetSha256)})`;
    })
    .join(",\n") + ";",
);
emit();

for (
  let offset = 0;
  offset < sourceRecords.length;
  offset += RECORD_BATCH_SIZE
) {
  const batch = sourceRecords.slice(offset, offset + RECORD_BATCH_SIZE);

  emit("INSERT INTO rdl041_source_record_stage (");
  emit(
    "  sheet_name, source_row_number, record_order, raw_row, row_sha256",
  );
  emit(") VALUES");
  emit(
    batch
      .map(
        (record) =>
          `  (${sqlText(record.sheetName)}, ${record.sourceRowNumber}, ${record.recordOrder}, ${jsonSql(record.rawRow)}, ${sqlText(record.rowSha256)})`,
      )
      .join(",\n") + ";",
  );
  emit();
}

emit("INSERT INTO rdl.rdl_source_sheet (");
emit(
  "  package_id, sheet_name, sheet_order, first_data_row_number, headers, source_row_count, sheet_sha256",
);
emit(")");
emit("SELECT");
emit("  p.package_id,");
emit("  stage.sheet_name,");
emit("  stage.sheet_order,");
emit("  stage.first_data_row_number,");
emit("  stage.headers,");
emit("  stage.source_row_count,");
emit("  stage.sheet_sha256");
emit("FROM rdl041_source_sheet_stage stage");
emit("JOIN rdl.rdl_package p");
emit(`  ON p.package_key = ${sqlText(packageKey)}`);
emit("WHERE NOT EXISTS (");
emit("  SELECT 1");
emit("  FROM rdl.rdl_source_sheet existing");
emit("  WHERE existing.package_id = p.package_id");
emit("    AND existing.sheet_name = stage.sheet_name");
emit(")");
emit("ORDER BY stage.sheet_order");
emit("ON CONFLICT (package_id, sheet_name) DO NOTHING;");
emit();
emit("INSERT INTO rdl.rdl_source_record (");
emit(
  "  package_id, source_sheet_id, source_row_number, record_order, raw_row, row_sha256",
);
emit(")");
emit("SELECT");
emit("  p.package_id,");
emit("  sheet.source_sheet_id,");
emit("  stage.source_row_number,");
emit("  stage.record_order,");
emit("  stage.raw_row,");
emit("  stage.row_sha256");
emit("FROM rdl041_source_record_stage stage");
emit("JOIN rdl.rdl_package p");
emit(`  ON p.package_key = ${sqlText(packageKey)}`);
emit("JOIN rdl.rdl_source_sheet sheet");
emit("  ON sheet.package_id = p.package_id");
emit(" AND sheet.sheet_name = stage.sheet_name");
emit("WHERE NOT EXISTS (");
emit("  SELECT 1");
emit("  FROM rdl.rdl_source_record existing");
emit("  WHERE existing.source_sheet_id = sheet.source_sheet_id");
emit("    AND existing.record_order = stage.record_order");
emit(")");
emit("ORDER BY sheet.sheet_order, stage.record_order");
emit("ON CONFLICT (source_sheet_id, record_order) DO NOTHING;");
emit();
emit("DO $rdl041_integrity$");
emit("DECLARE");
emit("  v_package_id bigint;");
emit("  v_expected_sheet_count integer;");
emit("  v_actual_sheet_count integer;");
emit("  v_expected_record_count integer;");
emit("  v_actual_record_count integer;");
emit("BEGIN");
emit("  SELECT package_id INTO v_package_id");
emit("  FROM rdl.rdl_package");
emit(`  WHERE package_key = ${sqlText(packageKey)};`);
emit();
emit("  SELECT count(*)::integer INTO v_expected_sheet_count");
emit("  FROM rdl041_source_sheet_stage;");
emit();
emit("  SELECT count(*)::integer INTO v_actual_sheet_count");
emit("  FROM rdl.rdl_source_sheet");
emit("  WHERE package_id = v_package_id;");
emit();
emit("  IF v_actual_sheet_count <> v_expected_sheet_count THEN");
emit(
  "    RAISE EXCEPTION 'Lossless source sheet count mismatch: expected %, actual %',",
);
emit(
  "      v_expected_sheet_count, v_actual_sheet_count USING ERRCODE = '23514';",
);
emit("  END IF;");
emit();
emit("  IF EXISTS (");
emit("    SELECT 1");
emit("    FROM (");
emit("      (");
emit("        SELECT");
emit("          sheet_name, sheet_order, first_data_row_number,");
emit("          headers, source_row_count, sheet_sha256");
emit("        FROM rdl.rdl_source_sheet");
emit("        WHERE package_id = v_package_id");
emit("        EXCEPT");
emit("        SELECT");
emit("          sheet_name, sheet_order, first_data_row_number,");
emit("          headers, source_row_count, sheet_sha256");
emit("        FROM rdl041_source_sheet_stage");
emit("      )");
emit("      UNION ALL");
emit("      (");
emit("        SELECT");
emit("          sheet_name, sheet_order, first_data_row_number,");
emit("          headers, source_row_count, sheet_sha256");
emit("        FROM rdl041_source_sheet_stage");
emit("        EXCEPT");
emit("        SELECT");
emit("          sheet_name, sheet_order, first_data_row_number,");
emit("          headers, source_row_count, sheet_sha256");
emit("        FROM rdl.rdl_source_sheet");
emit("        WHERE package_id = v_package_id");
emit("      )");
emit("    ) difference");
emit("  ) THEN");
emit(
  "    RAISE EXCEPTION 'Existing lossless source-sheet evidence differs from the governed snapshot' USING ERRCODE = '23514';",
);
emit("  END IF;");
emit();
emit("  SELECT count(*)::integer INTO v_expected_record_count");
emit("  FROM rdl041_source_record_stage;");
emit();
emit("  SELECT count(*)::integer INTO v_actual_record_count");
emit("  FROM rdl.rdl_source_record");
emit("  WHERE package_id = v_package_id;");
emit();
emit("  IF v_actual_record_count <> v_expected_record_count THEN");
emit(
  "    RAISE EXCEPTION 'Lossless source record count mismatch: expected %, actual %',",
);
emit(
  "      v_expected_record_count, v_actual_record_count USING ERRCODE = '23514';",
);
emit("  END IF;");
emit();
emit("  IF EXISTS (");
emit("    SELECT 1");
emit("    FROM (");
emit("      (");
emit("        SELECT");
emit("          sheet.sheet_name,");
emit("          sr.source_row_number,");
emit("          sr.record_order,");
emit("          sr.raw_row,");
emit("          sr.row_sha256");
emit("        FROM rdl.rdl_source_record sr");
emit("        JOIN rdl.rdl_source_sheet sheet");
emit("          ON sheet.source_sheet_id = sr.source_sheet_id");
emit("         AND sheet.package_id = sr.package_id");
emit("        WHERE sr.package_id = v_package_id");
emit("        EXCEPT");
emit("        SELECT");
emit("          sheet_name, source_row_number, record_order, raw_row, row_sha256");
emit("        FROM rdl041_source_record_stage");
emit("      )");
emit("      UNION ALL");
emit("      (");
emit("        SELECT");
emit("          sheet_name, source_row_number, record_order, raw_row, row_sha256");
emit("        FROM rdl041_source_record_stage");
emit("        EXCEPT");
emit("        SELECT");
emit("          sheet.sheet_name,");
emit("          sr.source_row_number,");
emit("          sr.record_order,");
emit("          sr.raw_row,");
emit("          sr.row_sha256");
emit("        FROM rdl.rdl_source_record sr");
emit("        JOIN rdl.rdl_source_sheet sheet");
emit("          ON sheet.source_sheet_id = sr.source_sheet_id");
emit("         AND sheet.package_id = sr.package_id");
emit("        WHERE sr.package_id = v_package_id");
emit("      )");
emit("    ) difference");
emit("  ) THEN");
emit(
  "    RAISE EXCEPTION 'Existing lossless source-record evidence differs from the governed snapshot' USING ERRCODE = '23514';",
);
emit("  END IF;");
emit("END;");
emit("$rdl041_integrity$;");
emit();
emit("INSERT INTO ingestion.ingestion_run (");
emit(
  "  package_id, source_uri, content_sha256, adapter_key, adapter_version, status, completed_at, validation_summary",
);
emit(")");
emit("SELECT");
emit("  p.package_id,");
emit("  p.source_uri,");
emit("  p.content_sha256,");
emit("  'cfihos-lossless-source-v1',");
emit("  '1.0.0',");
emit("  'completed',");
emit("  now(),");
emit("  jsonb_build_object(");
emit("    'sourceRecordContract', 'rdl-lossless-source/v1',");
emit(`    'snapshotSchema', ${sqlText(workbook.schema)},`);
emit(`    'sheetCount', ${workbook.sheetNames.length},`);
emit(`    'sourceRowCount', ${sourceRecords.length}`);
emit("  )");
emit("FROM rdl.rdl_package p");
emit(`WHERE p.package_key = ${sqlText(packageKey)}`);
emit("  AND NOT EXISTS (");
emit("    SELECT 1");
emit("    FROM ingestion.ingestion_run run");
emit("    WHERE run.package_id = p.package_id");
emit("      AND run.adapter_key = 'cfihos-lossless-source-v1'");
emit("      AND run.adapter_version = '1.0.0'");
emit("      AND run.content_sha256 = p.content_sha256");
emit("      AND run.status = 'completed'");
emit("  );");
emit();
emit("COMMIT;");
emit();
emit(
  `SELECT 'PASS RDL-041.1 lossless CFIHOS source ingestion: ${workbook.sheetNames.length} sheets / ${sourceRecords.length} rows' AS result;`,
);
