import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
function read(path: string): string { return readFileSync(new URL(`../${path}`, import.meta.url), "utf8"); }
const migration = read("database/migrations/025_create_external_standards_proposal_bundle_contract.sql");
const sqlTest = read("database/sql/test_rdl_045_external_proposal_bundle_contract.sql");
const repository = read("server/rdl/ExternalStandardsProposalBundleRepository.ts");
const service = read("server/rdl/ExternalStandardsProposalBundleService.ts");
const submitApi = read("api/proposals/bundle-submit.ts");
const statusApi = read("api/proposals/bundle-status.ts");
const reviewApi = read("api/proposals/bundle-review.ts");
const docs = read("docs/development/RDL_045_RDL_COMPLIANT_PROPOSAL_BUNDLES.md");
assert.match(migration, /external_standards_proposal_bundle/);
assert.match(migration, /external_standards_proposal_bundle_component/);
assert.match(migration, /external_standards_proposal_bundle_dependency/);
assert.match(migration, /external_standards_proposal_bundle_event/);
assert.match(migration, /submit_external_standards_proposal_bundle/);
assert.match(migration, /review_external_standards_proposal_bundle/);
assert.match(migration, /incomplete proposal bundle cannot be accepted/);
assert.match(migration, /UNIQUE \(source_system, external_request_key\)/);
assert.match(migration, /external_standards_proposal_bundle_queue/);
assert.match(sqlTest, /idempotency conflict was not rejected/);
assert.match(sqlTest, /incomplete bundle acceptance was not rejected/);
assert.match(repository, /external_standards_proposal_bundle_queue/);
assert.match(repository, /submit_external_standards_proposal_bundle/);
assert.match(repository, /review_external_standards_proposal_bundle/);
assert.match(service, /bundlePayload\.components/);
assert.match(service, /bundlePayload\.dependencies/);
assert.match(service, /sourcePseContentHash/);
assert.match(service, /stableJson/);
assert.match(submitApi, /rdl-external-standards-proposal-bundle\/v1/);
assert.match(statusApi, /rdl-external-standards-proposal-bundle-status\/v1/);
assert.match(reviewApi, /rdl-external-standards-proposal-bundle-review\/v1/);
assert.match(docs, /DATAGATE_022B_02_MAY_RESUME=NO/);
assert.match(docs, /Dependency closure/);
console.log("PASS RDL-045 external proposal bundle contract: database, API, service and documentation boundaries are present");
