import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read=(path:string)=>readFileSync(path,"utf8");
const migration=read("database/migrations/011_create_consumer_integration_notification.sql");
const repo=read("server/rdl/ConsumerIntegrationRepository.ts");
const service=read("server/rdl/ConsumerIntegrationService.ts");
const browser=read("src/rdl/consumerIntegrationService.ts");
const page=read("src/pages/RdlConsumerIntegrationPage.tsx");
const app=read("src/App.tsx");
const shell=read("src/components/AppShell.tsx");
const workflow=read(".github/workflows/build.yml");
const docs=read("docs/CONSUMER_INTEGRATION_CONTRACT.md");
const e2e=read("tests/e2e/explorer.spec.ts");
const a11y=read("tests/e2e/accessibility.spec.ts");
assert.ok(migration.includes("consumer_subscription")&&migration.includes("release_notification")&&migration.includes("consumer_release_state")&&migration.includes("consumer_pull_receipt"));
assert.ok(migration.includes("release must be staged before activation")&&migration.includes("enqueue_release_notifications")&&migration.includes("trg_notify_effective_standard_publication"));
assert.ok(repo.includes("request_key")&&repo.includes("lifecycle_status='staged'")&&repo.includes("lifecycle_status='activated'"));
assert.ok(service.includes("packageSha256")&&service.includes("requestKey"));
assert.ok(browser.includes("isSession")&&browser.includes('contentType.includes("application/json")')&&browser.includes('rdl-consumer-integration/v1'));
assert.ok(page.includes("Read-only integration demonstration")&&page.includes("Notify, pull, stage, activate")&&page.includes("no automatic downstream activation"));
assert.ok(app.includes('path="/integration"')&&shell.includes("Consumer Integration"));
assert.ok(workflow.includes("test:rdl-020"));
assert.ok(docs.includes("push notification, pull content")&&docs.includes("DataGate")&&docs.includes("idempotent"));
assert.ok(e2e.includes("consumer integration remains fail-closed and activation is explicit")&&a11y.includes('"/integration"'));
console.log("PASS RDL-020 consumer integration contract and change notification");
