import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read=(path:string)=>readFileSync(path,"utf8");
const migration=read("database/migrations/009_create_effective_standard_publication.sql");
const repository=read("server/rdl/EffectiveStandardPublicationRepository.ts");
const service=read("server/rdl/EffectiveStandardPublicationService.ts");
const browser=read("src/rdl/effectivePublicationService.ts");
const page=read("src/pages/RdlPublicationPage.tsx");
const api=read("api/publications/package.ts");
const e2e=read("tests/e2e/explorer.spec.ts");
const a11y=read("tests/e2e/accessibility.spec.ts");
const workflow=read(".github/workflows/build.yml");
assert.ok(migration.includes("effective_standard_release")&&migration.includes("immutable"),"RDL-018 must persist immutable release artifacts");
assert.ok(repository.includes("sha256")&&repository.includes("rdl-effective-standard-package/v1")&&repository.includes("Pending extension changes must be resolved"),"RDL-018 publication repository must hash packages and fail closed on pending governance");
assert.ok(service.includes("releaseVersion")&&service.includes("releaseKey"),"RDL-018 service must validate release identity");
assert.ok(browser.includes('contentType.includes("application/json")')&&browser.includes("isPublicationSession"),"RDL-018 browser session must reject SPA/non-JSON fallbacks and validate session shape");
assert.ok(page.includes("Read-only demonstration mode")&&page.includes("Parent vs proposed effective standard")&&page.includes("Publish immutable package"),"RDL-018 UX must expose comparison and honest fail-closed publication mode");
assert.ok(api.includes("Content-Disposition")&&api.includes("compositionSha256"),"RDL-018 package endpoint must expose a downloadable verifiable JSON package");
assert.ok(e2e.includes("effective standard publication remains fail-closed")&&e2e.includes('name: "Publish immutable package"'),"RDL-018 must include fail-closed browser E2E coverage");
assert.ok(a11y.includes('"/publication"'),"RDL-018 publication route must be in accessibility coverage");
assert.ok(workflow.includes("test:rdl-018"),"RDL-018 contract must run in CI");
console.log("PASS RDL-018 effective standard comparison and publication contract");
