import { createHash, randomUUID } from "node:crypto";
import type { SqlJsonClient } from "../db/PsqlJsonClient.ts";
import { sqlLiteral } from "../db/PsqlJsonClient.ts";

export type AiEvidenceItem = {
  id: string;
  kind: string;
  title: string;
  detail: string;
  source: "rdl" | "governance" | "application";
  authority: "direct" | "derived" | "candidate";
  route?: string;
};

export class AiStandardsIntelligenceRepository {
  constructor(private readonly client: SqlJsonClient) {}

  async collectEvidence(question: string, actor: string, limit = 18): Promise<AiEvidenceItem[]> {
    const safeLimit = Math.max(4, Math.min(30, Math.trunc(limit)));
    const terms = tokenize(question).slice(0, 8);
    const searchPattern = terms.length ? `%${terms.join("%")}%` : `%${question.trim().slice(0, 80)}%`;
    const evidence: AiEvidenceItem[] = [];

    const entities = await this.client.query<any>(`
      SELECT s.source_key,s.name AS source_name,r.version_label,p.package_key,e.entity_type_code,e.native_identifier,e.name,e.definition
      FROM rdl.rdl_entity e
      JOIN rdl.rdl_package p ON p.package_id=e.package_id
      JOIN rdl.rdl_release r ON r.release_id=p.release_id
      JOIN rdl.rdl_source s ON s.source_id=r.source_id
      WHERE e.native_identifier ILIKE ${sqlLiteral(searchPattern)}
         OR e.name ILIKE ${sqlLiteral(searchPattern)}
         OR COALESCE(e.definition,'') ILIKE ${sqlLiteral(searchPattern)}
      ORDER BY CASE WHEN lower(e.native_identifier)=lower(${sqlLiteral(question.trim())}) THEN 0 ELSE 1 END,e.name
      LIMIT ${Math.min(10, safeLimit)}
    `);
    for (const row of entities) evidence.push({
      id: `entity:${row.source_key}:${row.entity_type_code}:${row.native_identifier}`,
      kind: `${row.entity_type_code} · ${row.source_name}`,
      title: `${row.native_identifier} — ${row.name}`,
      detail: [row.definition, `Release ${row.version_label}`, `Package ${row.package_key}`].filter(Boolean).join(" · "),
      source: "rdl", authority: "direct",
      route: `/rdl/${encodeURIComponent(row.source_key)}/${encodeURIComponent(row.entity_type_code)}/${encodeURIComponent(row.native_identifier)}`,
    });

    const lower = question.toLowerCase();
    if (/release|change|breaking|impact|delta|version/.test(lower)) {
      const rows = await this.client.query<any>(`SELECT * FROM rdl.release_change_analysis_summary ORDER BY generated_at DESC LIMIT 4`);
      for (const row of rows) evidence.push({
        id: `impact:${row.release_change_analysis_id}`, kind: "Release impact analysis",
        title: `${row.from_release_key} ${row.from_release_version} → ${row.to_release_key} ${row.to_release_version}`,
        detail: `Immutable advisory analysis ${row.analysis_sha256}; generated by ${row.generated_by}.`,
        source: "governance", authority: "derived", route: "/impact",
      });
    }

    if (/migration|adopt|readiness|remediation|stage|activate/.test(lower)) {
      const rows = await this.client.query<any>(`SELECT * FROM rdl.release_migration_plan_summary ORDER BY updated_at DESC LIMIT 4`);
      for (const row of rows) evidence.push({
        id: `migration:${row.migration_plan_id}`, kind: "Migration plan",
        title: `${row.subject_type} ${row.subject_key}: ${row.title}`,
        detail: `Lifecycle ${row.lifecycle_status}; readiness ${row.readiness_status}; ${row.incomplete_action_count ?? 0} incomplete actions.`,
        source: "governance", authority: "direct", route: "/migration",
      });
    }

    if (/queue|priority|work|overdue|sla|assignment|review/.test(lower)) {
      const rows = await this.client.query<any>(`SELECT * FROM rdl.enterprise_work_queue_summary WHERE assignee_key=${sqlLiteral(actor)} AND status NOT IN ('completed','dismissed') ORDER BY due_at NULLS LAST LIMIT 5`);
      for (const row of rows) evidence.push({
        id: `work:${row.work_item_id}`, kind: "Assigned work item", title: row.title,
        detail: `Priority ${row.priority}; SLA ${row.sla_state}; status ${row.status}; source ${row.source_type}.`,
        source: "governance", authority: "direct", route: row.drill_through_path || "/work-queue",
      });
    }

    if (/control tower|portfolio|kpi|health|governance/.test(lower)) {
      const rows = await this.client.query<any>(`SELECT * FROM rdl.enterprise_standards_control_tower_kpi`);
      for (const row of rows.slice(0, 12)) evidence.push({
        id: `kpi:${row.metric_key ?? row.metric_name ?? evidence.length}`, kind: "Control Tower KPI",
        title: String(row.metric_label ?? row.metric_name ?? row.metric_key ?? "Enterprise standards KPI"),
        detail: `Value ${row.metric_value ?? row.value ?? 0}${row.metric_status ? `; status ${row.metric_status}` : ""}.`,
        source: "governance", authority: "derived", route: "/control-tower",
      });
    }

    return dedupe(evidence).slice(0, safeLimit);
  }

  async recordAdvisory(input: { actor: string; intent: string; question: string; evidence: AiEvidenceItem[]; answer: string; model: string; promptVersion: string }) {
    const answerSha256 = createHash("sha256").update(input.answer, "utf8").digest("hex");
    const advisoryKey = `ai-${randomUUID()}`;
    const manifest = JSON.stringify({ schemaVersion: "rdl-ai-evidence/v1", items: input.evidence });
    const rows = await this.client.query<any>(`INSERT INTO rdl.ai_advisory_run(advisory_key,actor_key,intent,question,evidence_manifest,answer_text,answer_sha256,model_key,prompt_version)
      VALUES(${sqlLiteral(advisoryKey)},${sqlLiteral(input.actor)},${sqlLiteral(input.intent)},${sqlLiteral(input.question)},${sqlLiteral(manifest)}::jsonb,${sqlLiteral(input.answer)},${sqlLiteral(answerSha256)},${sqlLiteral(input.model)},${sqlLiteral(input.promptVersion)}) RETURNING ai_advisory_run_id,advisory_key,answer_sha256,prompt_version,created_at`);
    return rows[0] ?? null;
  }
}

function tokenize(text: string) {
  return text.toLowerCase().replace(/[^a-z0-9_-]+/g, " ").split(/\s+/).filter(x => x.length >= 3 && !["the","and","for","with","what","why","how","this","that","from"].includes(x));
}
function dedupe(items: AiEvidenceItem[]) { const seen=new Set<string>(); return items.filter(i=>!seen.has(i.id) && Boolean(seen.add(i.id))); }
