import { IDENTITY_ADMIN_ROLE, type EnterpriseSsoIdentity } from "../auth/EnterpriseIdentity.ts";
import { EnterpriseIdentityRepository } from "./EnterpriseIdentityRepository.ts";

export const ENTERPRISE_ROLES=["rdl-mapping-reviewer","rdl-extension-reviewer","rdl-package-consumer","rdl-migration-approver","rdl-work-queue-coordinator","rdl-ai-standards-analyst",IDENTITY_ADMIN_ROLE] as const;
export class EnterpriseIdentityService {
  constructor(private readonly repository:EnterpriseIdentityRepository){}
  async session(identity:EnterpriseSsoIdentity){const user=await this.repository.upsertUser(identity);const roles=user.status==="active"?await this.repository.effectiveRoles(identity.subject,identity.groups):[];return{authenticated:true,subject:identity.subject,email:identity.email,displayName:identity.displayName,groups:identity.groups,roles,status:user.status,authenticatedAt:identity.authenticatedAt,contract:"rdl-enterprise-identity/v1" as const}}
  async adminSummary(identity:EnterpriseSsoIdentity,authorizedRoles?:string[]){const session=await this.session(identity);requireAdmin(authorizedRoles??session.roles);return{schemaVersion:"rdl-enterprise-identity-admin/v1" as const,generatedAt:new Date().toISOString(),users:await this.repository.directory(),groupMappings:await this.repository.groupMappings(),availableRoles:[...ENTERPRISE_ROLES]}}
  assignRole(actor:EnterpriseSsoIdentity,actorRoles:string[],input:{subject:string;role:string;rationale:string}){requireAdmin(actorRoles);validateRole(input.role);if(actor.subject===input.subject&&input.role===IDENTITY_ADMIN_ROLE)throw new Error("Identity administrators cannot grant the identity-admin role to themselves.");return this.repository.assignRole(req(input.subject,"subject"),input.role,actor.subject,req(input.rationale,"rationale"))}
  revokeRole(actor:EnterpriseSsoIdentity,actorRoles:string[],input:{subject:string;role:string;rationale:string}){requireAdmin(actorRoles);validateRole(input.role);if(actor.subject===input.subject&&input.role===IDENTITY_ADMIN_ROLE)throw new Error("Identity administrators cannot revoke their own identity-admin role.");return this.repository.revokeRole(req(input.subject,"subject"),input.role,actor.subject,req(input.rationale,"rationale"))}
  setUserStatus(actor:EnterpriseSsoIdentity,actorRoles:string[],input:{subject:string;status:"active"|"disabled";rationale:string}){requireAdmin(actorRoles);if(actor.subject===input.subject&&input.status==="disabled")throw new Error("Identity administrators cannot disable their own account.");if(!["active","disabled"].includes(input.status))throw new Error("status is invalid.");return this.repository.setUserStatus(req(input.subject,"subject"),input.status,actor.subject,req(input.rationale,"rationale"))}
  changeGroupMapping(actor:EnterpriseSsoIdentity,actorRoles:string[],input:{action:"create"|"disable";group:string;role:string;rationale:string}){requireAdmin(actorRoles);validateRole(input.role);const group=req(input.group,"group");const rationale=req(input.rationale,"rationale");return input.action==="create"?this.repository.createGroupMapping(group,input.role,actor.subject,rationale):this.repository.disableGroupMapping(group,input.role,actor.subject,rationale)}
}
function requireAdmin(roles:string[]){if(!roles.includes(IDENTITY_ADMIN_ROLE))throw new Error("The authenticated user is not authorized for identity administration.")}
function validateRole(role:string){if(!(ENTERPRISE_ROLES as readonly string[]).includes(role))throw new Error("role is invalid.")}
function req(v:string,n:string){const x=String(v??"").trim();if(!x)throw new Error(`${n} is required.`);return x}
