import type { SqlJsonClient } from "../db/PsqlJsonClient.ts";
import { sqlLiteral } from "../db/PsqlJsonClient.ts";

export class EnterpriseTenantRepository{
  constructor(private readonly client:SqlJsonClient){}
  organizations(){return this.client.query<any>(`SELECT * FROM rdl.enterprise_tenant_directory ORDER BY display_name,organization_key`)}
  memberships(subject:string){return this.client.query<any>(`SELECT m.organization_key,o.display_name,o.status,m.status AS membership_status FROM rdl.enterprise_organization_membership m JOIN rdl.enterprise_organization o USING(organization_key) WHERE m.subject_key=${sqlLiteral(subject)} AND m.revoked_at IS NULL ORDER BY o.display_name`)}
  members(org:string){return this.client.query<any>(`SELECT m.subject_key,u.email,u.display_name,m.status,m.membership_source,m.assigned_at,COALESCE((SELECT array_agg(r.role_key ORDER BY r.role_key) FROM rdl.enterprise_tenant_role_assignment r WHERE r.organization_key=m.organization_key AND r.subject_key=m.subject_key AND r.revoked_at IS NULL),ARRAY[]::text[]) AS tenant_roles FROM rdl.enterprise_organization_membership m JOIN rdl.enterprise_identity_user u USING(subject_key) WHERE m.organization_key=${sqlLiteral(org)} AND m.revoked_at IS NULL ORDER BY u.display_name,u.email`)}
  configuration(org:string){return this.client.query<any>(`SELECT config_key,config_value,updated_by,updated_at FROM rdl.enterprise_organization_configuration WHERE organization_key=${sqlLiteral(org)} ORDER BY config_key`)}
  bindings(org:string){return this.client.query<any>(`SELECT resource_type,resource_key,bound_by,bound_at FROM rdl.enterprise_tenant_resource_binding WHERE organization_key=${sqlLiteral(org)} ORDER BY resource_type,resource_key`)}
  async effectiveTenantRoles(org:string,subject:string){const rows=await this.client.query<any>(`SELECT role_key FROM rdl.enterprise_tenant_role_assignment WHERE organization_key=${sqlLiteral(org)} AND subject_key=${sqlLiteral(subject)} AND revoked_at IS NULL ORDER BY role_key`);return rows.map(r=>String(r.role_key))}
  async hasMembership(org:string,subject:string){const rows=await this.client.query<any>(`SELECT 1 AS ok FROM rdl.enterprise_organization_membership m JOIN rdl.enterprise_organization o USING(organization_key) WHERE m.organization_key=${sqlLiteral(org)} AND m.subject_key=${sqlLiteral(subject)} AND m.status='active' AND m.revoked_at IS NULL AND o.status='active' LIMIT 1`);return Boolean(rows[0])}
  async createOrganization(key:string,name:string,actor:string,rationale:string){const rows=await this.client.query<any>(`INSERT INTO rdl.enterprise_organization(organization_key,display_name,created_by) VALUES(${sqlLiteral(key)},${sqlLiteral(name)},${sqlLiteral(actor)}) RETURNING *`);await this.audit(key,"organization_created",actor,null,null,null,rationale);return rows[0]}
  async addMember(org:string,subject:string,actor:string,rationale:string){const rows=await this.client.query<any>(`INSERT INTO rdl.enterprise_organization_membership(organization_key,subject_key,assigned_by) VALUES(${sqlLiteral(org)},${sqlLiteral(subject)},${sqlLiteral(actor)}) ON CONFLICT(organization_key,subject_key,membership_source,source_group_key) DO UPDATE SET status='active',revoked_at=NULL,revoked_by=NULL,revoke_reason=NULL,assigned_by=excluded.assigned_by,assigned_at=now() RETURNING *`);await this.audit(org,"member_added",actor,subject,null,null,rationale);return rows[0]}
  async removeMember(org:string,subject:string,actor:string,rationale:string){const rows=await this.client.query<any>(`UPDATE rdl.enterprise_organization_membership SET status='disabled',revoked_at=now(),revoked_by=${sqlLiteral(actor)},revoke_reason=${sqlLiteral(rationale)} WHERE organization_key=${sqlLiteral(org)} AND subject_key=${sqlLiteral(subject)} AND revoked_at IS NULL RETURNING *`);if(!rows[0])throw new Error("Active tenant membership not found.");await this.audit(org,"member_removed",actor,subject,null,null,rationale);return rows[0]}
  async assignTenantRole(org:string,subject:string,role:string,actor:string,rationale:string){const rows=await this.client.query<any>(`INSERT INTO rdl.enterprise_tenant_role_assignment(organization_key,subject_key,role_key,assigned_by) VALUES(${sqlLiteral(org)},${sqlLiteral(subject)},${sqlLiteral(role)},${sqlLiteral(actor)}) ON CONFLICT(organization_key,subject_key,role_key) DO UPDATE SET revoked_at=NULL,revoked_by=NULL,revoke_reason=NULL,assigned_by=excluded.assigned_by,assigned_at=now() RETURNING *`);await this.audit(org,"tenant_role_assigned",actor,subject,"role",role,rationale);return rows[0]}
  async revokeTenantRole(org:string,subject:string,role:string,actor:string,rationale:string){const rows=await this.client.query<any>(`UPDATE rdl.enterprise_tenant_role_assignment SET revoked_at=now(),revoked_by=${sqlLiteral(actor)},revoke_reason=${sqlLiteral(rationale)} WHERE organization_key=${sqlLiteral(org)} AND subject_key=${sqlLiteral(subject)} AND role_key=${sqlLiteral(role)} AND revoked_at IS NULL RETURNING *`);if(!rows[0])throw new Error("Active tenant role assignment not found.");await this.audit(org,"tenant_role_revoked",actor,subject,"role",role,rationale);return rows[0]}
  async setConfiguration(org:string,key:string,value:unknown,actor:string,rationale:string){const json=sqlLiteral(JSON.stringify(value));const rows=await this.client.query<any>(`INSERT INTO rdl.enterprise_organization_configuration(organization_key,config_key,config_value,updated_by) VALUES(${sqlLiteral(org)},${sqlLiteral(key)},${json}::jsonb,${sqlLiteral(actor)}) ON CONFLICT(organization_key,config_key) DO UPDATE SET config_value=excluded.config_value,updated_by=excluded.updated_by,updated_at=now() RETURNING *`);await this.audit(org,"configuration_changed",actor,null,"configuration",key,rationale);return rows[0]}
  async bindResource(org:string,type:string,key:string,actor:string,rationale:string){const rows=await this.client.query<any>(`INSERT INTO rdl.enterprise_tenant_resource_binding(organization_key,resource_type,resource_key,bound_by) VALUES(${sqlLiteral(org)},${sqlLiteral(type)},${sqlLiteral(key)},${sqlLiteral(actor)}) RETURNING *`);await this.audit(org,"resource_bound",actor,null,type,key,rationale);return rows[0]}
  async assertResourceAccess(org:string,type:string,key:string){await this.client.query(`SELECT rdl.assert_tenant_resource_access(${sqlLiteral(org)},${sqlLiteral(type)},${sqlLiteral(key)})`);return true}
  async audit(org:string,event:string,actor:string,subject:string|null,type:string|null,key:string|null,rationale:string){await this.client.query(`INSERT INTO rdl.enterprise_tenant_audit_event(organization_key,event_type,actor_subject_key,target_subject_key,target_resource_type,target_resource_key,rationale) VALUES(${sqlLiteral(org)},${sqlLiteral(event)},${sqlLiteral(actor)},${subject?sqlLiteral(subject):"NULL"},${type?sqlLiteral(type):"NULL"},${key?sqlLiteral(key):"NULL"},${sqlLiteral(rationale)}) RETURNING tenant_audit_event_id`)}
}
