import { IDENTITY_ADMIN_ROLE,type EnterpriseSsoIdentity } from "../auth/EnterpriseIdentity.ts";
import { TENANT_ADMIN_ROLE,TenantIsolationError } from "../auth/EnterpriseTenantContext.ts";
import { EnterpriseTenantRepository } from "./EnterpriseTenantRepository.ts";

const TENANT_RESOURCE_TYPES=["enterprise_context","extension","published_release","consumer","migration_plan","work_item","ai_advisory_run","ai_evaluation"] as const;
export class EnterpriseTenantService{
  constructor(private readonly repository:EnterpriseTenantRepository){}
  async tenantSession(identity:EnterpriseSsoIdentity,organizationKey:string,globalRoles:string[]){const member=await this.repository.hasMembership(organizationKey,identity.subject);if(!member)throw new TenantIsolationError(403,"The authenticated user is not an active member of this organization.");const tenantRoles=await this.repository.effectiveTenantRoles(organizationKey,identity.subject);return{authenticated:true,organizationKey,subject:identity.subject,email:identity.email,displayName:identity.displayName,globalRoles,tenantRoles,contract:"rdl-enterprise-tenant-session/v1" as const}}
  async adminSummary(identity:EnterpriseSsoIdentity,organizationKey:string,globalRoles:string[]){const session=await this.tenantSession(identity,organizationKey,globalRoles);requireTenantAdmin(globalRoles,session.tenantRoles);return{schemaVersion:"rdl-enterprise-tenant-admin/v1" as const,generatedAt:new Date().toISOString(),organizationKey,organizations:await this.repository.organizations(),members:await this.repository.members(organizationKey),configuration:await this.repository.configuration(organizationKey),bindings:await this.repository.bindings(organizationKey),resourceTypes:[...TENANT_RESOURCE_TYPES]}}
  async accessibleOrganizations(identity:EnterpriseSsoIdentity){return this.repository.memberships(identity.subject)}
  async createOrganization(identity:EnterpriseSsoIdentity,globalRoles:string[],input:{organizationKey:string;displayName:string;rationale:string}){if(!globalRoles.includes(IDENTITY_ADMIN_ROLE))throw new TenantIsolationError(403,"Only identity administrators can create organizations.");const key=org(input.organizationKey);const rationale=req(input.rationale,"rationale");const created=await this.repository.createOrganization(key,req(input.displayName,"displayName"),identity.subject,rationale);await this.repository.addMember(key,identity.subject,identity.subject,"Organization creator bootstrap membership.");await this.repository.assignTenantRole(key,identity.subject,TENANT_ADMIN_ROLE,identity.subject,"Organization creator bootstrap tenant administration.");return created}
  async changeMember(identity:EnterpriseSsoIdentity,organizationKey:string,globalRoles:string[],input:{action:"add"|"remove";subject:string;rationale:string}){const session=await this.tenantSession(identity,organizationKey,globalRoles);requireTenantAdmin(globalRoles,session.tenantRoles);if(identity.subject===input.subject&&input.action==="remove")throw new Error("Tenant administrators cannot remove their own active tenant membership.");return input.action==="add"?this.repository.addMember(organizationKey,req(input.subject,"subject"),identity.subject,req(input.rationale,"rationale")):this.repository.removeMember(organizationKey,req(input.subject,"subject"),identity.subject,req(input.rationale,"rationale"))}
  async changeTenantRole(identity:EnterpriseSsoIdentity,organizationKey:string,globalRoles:string[],input:{action:"assign"|"revoke";subject:string;role:string;rationale:string}){const session=await this.tenantSession(identity,organizationKey,globalRoles);requireTenantAdmin(globalRoles,session.tenantRoles);if(identity.subject===input.subject&&input.role===TENANT_ADMIN_ROLE)throw new Error("Tenant administrators cannot grant or revoke their own tenant-admin role.");const role=req(input.role,"role");return input.action==="assign"?this.repository.assignTenantRole(organizationKey,req(input.subject,"subject"),role,identity.subject,req(input.rationale,"rationale")):this.repository.revokeTenantRole(organizationKey,req(input.subject,"subject"),role,identity.subject,req(input.rationale,"rationale"))}
  async setConfiguration(identity:EnterpriseSsoIdentity,organizationKey:string,globalRoles:string[],input:{key:string;value:unknown;rationale:string}){const session=await this.tenantSession(identity,organizationKey,globalRoles);requireTenantAdmin(globalRoles,session.tenantRoles);return this.repository.setConfiguration(organizationKey,req(input.key,"key"),input.value,identity.subject,req(input.rationale,"rationale"))}
  async bindResource(identity:EnterpriseSsoIdentity,organizationKey:string,globalRoles:string[],input:{resourceType:string;resourceKey:string;rationale:string}){const session=await this.tenantSession(identity,organizationKey,globalRoles);requireTenantAdmin(globalRoles,session.tenantRoles);if(!TENANT_RESOURCE_TYPES.includes(input.resourceType as any))throw new Error("resourceType is invalid.");return this.repository.bindResource(organizationKey,input.resourceType,req(input.resourceKey,"resourceKey"),identity.subject,req(input.rationale,"rationale"))}
  async assertResourceAccess(identity:EnterpriseSsoIdentity,organizationKey:string,type:string,key:string,globalRoles:string[]){await this.tenantSession(identity,organizationKey,globalRoles);await this.repository.assertResourceAccess(organizationKey,type,key);return{allowed:true,organizationKey,resourceType:type,resourceKey:key,contract:"rdl-tenant-resource-access/v1" as const}}
}
function requireTenantAdmin(globalRoles:string[],tenantRoles:string[]){if(!globalRoles.includes(IDENTITY_ADMIN_ROLE)&&!tenantRoles.includes(TENANT_ADMIN_ROLE))throw new TenantIsolationError(403,"The authenticated user is not authorized for tenant administration.")}
function req(value:string,name:string){const v=value?.trim();if(!v)throw new Error(`${name} is required.`);return v}
function org(value:string){const v=req(value,"organizationKey").toLowerCase();if(!/^[a-z0-9][a-z0-9._-]{1,79}$/.test(v))throw new Error("organizationKey is invalid.");return v}
