import { createHash } from "node:crypto";
import type { SqlJsonClient } from "../db/PsqlJsonClient.ts";
import { sqlLiteral } from "../db/PsqlJsonClient.ts";

export type ReleaseDeltaKind="added"|"removed"|"modified"|"unchanged";
export type ReleaseImpactItem={key:string;entityType:string;nativeIdentifier:string;kind:ReleaseDeltaKind;breaking:boolean;fromName?:string;toName?:string;sourceLayer?:string;rationale?:string};
export type ReleaseImpactAnalysis={contract:"rdl-release-impact/v1";fromRelease:{id:number;key:string;version:string};toRelease:{id:number;key:string;version:string};items:ReleaseImpactItem[];summary:{added:number;removed:number;modified:number;unchanged:number;breaking:number;nonBreaking:number};consumerImpact:{discovered:number;staged:number;activated:number;rejected:number};releaseNotes:{title:string;highlights:string[]};analysisSha256:string};

export class ReleaseChangeIntelligenceRepository {
  constructor(private readonly client:SqlJsonClient){}
  async releases(limit=100){return this.client.query<any>(`SELECT release_id,context_key,context_name,release_key,release_version,lifecycle_status,published_at FROM rdl.distributed_effective_standard_release ORDER BY published_at DESC LIMIT ${Math.max(1,Math.min(500,Math.trunc(limit)))}`);}
  async compare(fromReleaseId:number,toReleaseId:number):Promise<ReleaseImpactAnalysis>{
    const rows=await this.client.query<any>(`SELECT effective_standard_release_id,release_key,release_version,package_payload FROM rdl.effective_standard_release WHERE effective_standard_release_id IN (${fromReleaseId},${toReleaseId})`);
    const from=rows.find((r:any)=>Number(r.effective_standard_release_id)===fromReleaseId);const to=rows.find((r:any)=>Number(r.effective_standard_release_id)===toReleaseId);
    if(!from||!to)throw new Error("Both published releases are required.");
    const fromItems=normalize(from.package_payload?.changes);const toItems=normalize(to.package_payload?.changes);const keys=new Set([...fromItems.keys(),...toItems.keys()]);const items:ReleaseImpactItem[]=[];
    for(const key of [...keys].sort()){const a=fromItems.get(key),b=toItems.get(key);if(!a&&b){items.push(item(key,b,"added",false));continue;}if(a&&!b){items.push(item(key,a,"removed",true));continue;}if(!a||!b)continue;const changed=stable(a)!==stable(b);items.push({key,entityType:String(b.entityType??a.entityType??"unknown"),nativeIdentifier:String(b.nativeIdentifier??a.nativeIdentifier??key),kind:changed?"modified":"unchanged",breaking:changed&&isBreaking(a,b),fromName:text(a.effectiveName??a.inheritedName),toName:text(b.effectiveName??b.inheritedName),sourceLayer:text(b.sourceLayer),rationale:text(b.rationale)});}
    const summary={added:count(items,"added"),removed:count(items,"removed"),modified:count(items,"modified"),unchanged:count(items,"unchanged"),breaking:items.filter(i=>i.breaking).length,nonBreaking:items.filter(i=>i.kind!=="unchanged"&&!i.breaking).length};
    const impactRows=await this.client.query<any>(`SELECT lifecycle_status,count(*)::integer AS count FROM rdl.consumer_release_state WHERE effective_standard_release_id=${fromReleaseId} GROUP BY lifecycle_status`);const consumerImpact={discovered:0,staged:0,activated:0,rejected:0};for(const row of impactRows){const k=row.lifecycle_status as keyof typeof consumerImpact;if(k in consumerImpact)consumerImpact[k]=Number(row.count);}
    const releaseNotes={title:`${from.release_key} ${from.release_version} → ${to.release_version}`,highlights:[`${summary.added} added`,`${summary.modified} modified`,`${summary.removed} removed`,`${summary.breaking} potentially breaking`]};
    const base={contract:"rdl-release-impact/v1" as const,fromRelease:{id:fromReleaseId,key:from.release_key,version:from.release_version},toRelease:{id:toReleaseId,key:to.release_key,version:to.release_version},items,summary,consumerImpact,releaseNotes};const analysisSha256=createHash("sha256").update(stable(base)).digest("hex");return {...base,analysisSha256};
  }
  async persist(fromReleaseId:number,toReleaseId:number,generatedBy:string){const analysis=await this.compare(fromReleaseId,toReleaseId);const rows=await this.client.query<any>(`INSERT INTO rdl.release_change_analysis(from_release_id,to_release_id,change_summary,impact_summary,release_notes,analysis_sha256,generated_by) VALUES(${fromReleaseId},${toReleaseId},${sqlLiteral(JSON.stringify(analysis.summary))}::jsonb,${sqlLiteral(JSON.stringify(analysis.consumerImpact))}::jsonb,${sqlLiteral(JSON.stringify(analysis.releaseNotes))}::jsonb,${sqlLiteral(analysis.analysisSha256)},${sqlLiteral(generatedBy)}) ON CONFLICT (from_release_id,to_release_id,analysis_contract) DO UPDATE SET generated_by=rdl.release_change_analysis.generated_by RETURNING release_change_analysis_id,analysis_sha256,generated_at`);return {analysis,...rows[0]};}
}
function normalize(value:unknown){const map=new Map<string,any>();for(const raw of Array.isArray(value)?value:[]){if(!raw||typeof raw!=="object")continue;const r=raw as Record<string,unknown>;const key=`${String(r.entityType??"unknown")}:${String(r.nativeIdentifier??r.extensionChangeId??"")}`;map.set(key,r);}return map;}
function item(key:string,r:any,kind:ReleaseDeltaKind,breaking:boolean):ReleaseImpactItem{return {key,entityType:String(r.entityType??"unknown"),nativeIdentifier:String(r.nativeIdentifier??key),kind,breaking,toName:text(r.effectiveName??r.inheritedName),sourceLayer:text(r.sourceLayer),rationale:text(r.rationale)}}
function isBreaking(a:any,b:any){return a.changeKind==="retire"||b.changeKind==="retire"||String(a.entityType??"")!==String(b.entityType??"")||String(a.effectiveName??"")!==String(b.effectiveName??"");}
function stable(v:unknown):string{if(Array.isArray(v))return `[${v.map(stable).join(",")}]`;if(v&&typeof v==="object")return `{${Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,val])=>`${JSON.stringify(k)}:${stable(val)}`).join(",")}}`;return JSON.stringify(v);}
function count(items:ReleaseImpactItem[],kind:ReleaseDeltaKind){return items.filter(i=>i.kind===kind).length;}function text(v:unknown){return typeof v==="string"&&v.trim()?v:undefined;}
